import {authState,canonicalSport,dayKey,edge,esc,rest} from './training-data.js?v=20260911overhaul110';

const CSS='./advice-state.css?v=20260911overhaul110',TASK_KEY='traininglab-advice-checks-v1';
let cache=null,loading=false,lastLoad=0;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const defaults={football:8,futsal:8,run:5,cycling:4,gym:7,walk:2,other:4,recovery:2};
const legFactor={football:1,futsal:1,run:.88,cycling:.72,gym:.62,walk:.25,other:.3,recovery:.15};
const labels={football:'Fútbol',futsal:'Fútbol sala',run:'Running',cycling:'Ciclismo',gym:'Fuerza',walk:'Caminata',other:'Actividad'};
const emoji=t=>({football:'⚽',futsal:'⚽',run:'🏃',cycling:'🚴',gym:'🏋️',walk:'🚶'}[canonicalSport(t)]||'●');
function css(){if(document.querySelector('link[data-advice-state]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.adviceState='1';document.head.append(l)}
function since(days){const d=new Date();d.setDate(d.getDate()-days);return dayKey(d)}
async function load(force=false){if(loading)return cache;if(!force&&cache&&Date.now()-lastLoad<20000)return cache;if(!authState()?.access_token)return null;loading=true;try{
 const activities=await rest('activities',{select:'id,activity_date,started_at,activity_type,source,title,duration_min,moving_time_min,rpe,distance_km,avg_hr,max_hr,calories,high_intensity_m,metrics',activity_date:`gte.${since(14)}`,order:'activity_date.desc,started_at.desc.nullslast',limit:80});
 const ids=(activities||[]).map(x=>x.id).filter(Boolean),analyses=ids.length?await rest('activity_analysis',{select:'activity_id,summary,report,hr_zones,speed_zones',activity_id:`in.(${ids.join(',')})`}):[];
 const [sleep,injuries,checkins,statuses]=await Promise.all([
  rest('sleep_records',{select:'sleep_date,sleep_start,sleep_end,total_sleep_min,deep_sleep_min,rem_sleep_min,light_sleep_min,awake_min,sleep_score,avg_hrv,resting_hr,metrics',sleep_date:`gte.${since(9)}`,order:'sleep_date.desc',limit:14}).catch(()=>[]),
  rest('injuries',{select:'id,body_area,side,pain_score,status,trigger,advice,red_flags,updated_at',status:'eq.active',order:'updated_at.desc',limit:20}).catch(()=>[]),
  rest('daily_checkins',{select:'checkin_date,energy,soreness,stress,mood,motivation,sleep_quality,notes,answers,created_at',checkin_date:`gte.${since(14)}`,order:'checkin_date.desc',limit:20}).catch(()=>[]),
  rest('daily_status',{select:'day,fatigue,rest_requested,football_override,football_time,notes,updated_at',day:`gte.${since(7)}`,order:'day.desc',limit:14}).catch(()=>[])
 ]);
 const map=new Map((analyses||[]).map(x=>[String(x.activity_id),x]));cache={activities:(activities||[]).map(a=>({...a,analysis:map.get(String(a.id))||null})),sleep:sleep||[],injuries:injuries||[],checkins:checkins||[],statuses:statuses||[]};lastLoad=Date.now();return cache
 }finally{loading=false}}
function activityDate(a){const d=a.started_at?new Date(a.started_at):new Date(`${a.activity_date}T12:00:00`);return Number.isNaN(+d)?null:d}
function hoursAgo(a){const d=activityDate(a);return d?Math.max(0,(Date.now()-d.getTime())/36e5):999}
function rpe(a){const n=Number(a.rpe);return n>0?n:(defaults[canonicalSport(a.activity_type)]||4)}
function stress(a){const min=Math.max(0,Number(a.moving_time_min||a.duration_min)||0);return min*rpe(a)*Math.exp(-hoursAgo(a)/48)}
function model(data){const recent=(data.activities||[]).filter(a=>hoursAgo(a)<=96),load=recent.reduce((s,a)=>s+stress(a),0),legLoad=recent.reduce((s,a)=>s+stress(a)*(legFactor[canonicalSport(a.activity_type)]??.4),0),status=data.statuses?.find(x=>x.day===dayKey()),check=data.checkins?.find(x=>x.checkin_date===dayKey())||data.checkins?.[0],manual=Number(status?.fatigue||check?.answers?.state_analysis?.fatigue||0),sleepMin=Number(data.sleep?.[0]?.total_sleep_min)||null,sleepAdj=sleepMin==null?0:clamp((sleepMin-420)/60,-1.2,1.2)*6,fatigue=clamp(Math.round(manual||1+load/280),1,5),legs=Math.round(clamp(100-legLoad/8+sleepAdj,18,100)),readiness=Math.round(clamp(100-load/11-(fatigue-1)*6+sleepAdj,18,100));return{load,legLoad,fatigue,legs,readiness,sleepMin,status,check}}
function monday(){const d=new Date(),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(0,0,0,0);return d}
function week(data){const start=monday(),out=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dayKey(d),acts=data.activities.filter(a=>a.activity_date===key);out.push(`<div class="advice-day ${key===dayKey()?'is-today':''}"><span>${d.toLocaleDateString('es-ES',{weekday:'short'}).replace('.','')}</span><b>${d.getDate()}</b><div>${acts.map(a=>`<i title="${esc(labels[canonicalSport(a.activity_type)]||'Actividad')}">${emoji(a.activity_type)}</i>`).join('')||'<small>·</small>'}</div></div>`)}return out.join('')}
function latest(data){return [...data.activities].sort((a,b)=>(activityDate(b)?.getTime()||0)-(activityDate(a)?.getTime()||0))[0]||null}
function advice(data,m){const last=latest(data),sport=canonicalSport(last?.activity_type),age=last?hoursAgo(last):999,hard=last&&rpe(last)>=7,out=[];
 out.push({icon:'♻️',title:'Recuperación',text:last&&age<30?(hard?`Vienes de ${String(labels[sport]||'actividad').toLowerCase()} exigente. Prioriza movimiento suave, hidratación y deja que esa sesión cuente antes de añadir intensidad.`:`La última sesión fue ${String(labels[sport]||'actividad').toLowerCase()}. Observa cómo responden las piernas antes de añadir trabajo duro.`):(m.legs<55?'Las piernas siguen con carga acumulada de los últimos días. Evita juntar dos estímulos duros solo para completar volumen.':'La carga reciente permite entrenar, pero la sensación real manda si aparece dolor o fatiga inusual.')});
 const warm={football:'12–15 min: trote, movilidad dinámica, activación, progresiones y balón. Sin sprint máximo en frío.',futsal:'10–12 min: movilidad, cambios de dirección progresivos y aceleraciones cortas sin llegar al máximo.',run:'8–10 min: caminar/trote suave, tobillo-cadera y 3 progresiones cómodas antes de subir ritmo.',cycling:'5–8 min de pedaleo fácil antes de subir resistencia o potencia.',gym:'Haz 1–3 series de aproximación del primer ejercicio y aumenta carga gradualmente; no empieces con la serie dura.'}[sport]||'Empieza con 5–10 min progresivos antes de cualquier trabajo intenso.';out.push({icon:'🔥',title:'Calentamiento',text:warm});
 out.push({icon:'🍚',title:'Alimentación',text:hard&&age<8?'Tras una sesión exigente: comida normal con una fuente clara de proteína, carbohidratos suficientes y líquidos.':sport==='football'||sport==='futsal'?'En día de partido prioriza carbohidratos en las comidas previas y evita llegar con hambre; reparte la proteína durante el día.':'Reparte proteína durante el día y ajusta carbohidratos a la carga que realmente has hecho, no a la que estaba prevista.'});
 out.push({icon:'🌙',title:'Descanso',text:m.sleepMin!=null&&m.sleepMin<420?'La última noche quedó por debajo de 7 h. No compenses con más intensidad: protege la siguiente ventana de sueño.':'Mantén tu ventana habitual y juzga el descanso por tendencia de varias noches, no por una sola cifra.'});
 const inj=data.injuries?.[0];out.push({icon:'🩹',title:'Molestias',text:inj?`Hay una molestia activa en ${inj.body_area}${inj.side?' ('+inj.side+')':''}${inj.pain_score?' · '+inj.pain_score+'/10':''}. Reduce la carga que la agrave; si empeora claramente o aparece una señal de alarma, busca valoración sanitaria.`:'No hay una lesión activa registrada. Si notas algo nuevo, cuéntalo en Mi estado para incorporarlo al mapa corporal y a los consejos.'});return out}
function taskMap(){try{return JSON.parse(localStorage.getItem(TASK_KEY)||'{}')||{}}catch{return{}}}
function taskSet(code,done){const s=taskMap();s[`${dayKey()}:${code}`]=!!done;localStorage.setItem(TASK_KEY,JSON.stringify(s))}
function tasks(data,m){const s=taskMap(),now=new Date(),h=now.getHours(),status=data.statuses?.find(x=>x.day===dayKey()),arr=[];
 if(h>=12&&h<15)arr.push(['desayuno','Haz tu primera comida completa','Proteína + carbohidratos; marca el check cuando esté hecho.']);else if(h>=15&&h<18)arr.push(['comida','Comida principal','Repón energía con una comida completa según la carga real.']);else if(h>=18&&h<21)arr.push(['merienda','Merienda','Si faltan horas para cenar o queda actividad, una merienda útil evita llegar vacío.']);else if(h>=21||h<1)arr.push(['cena','Cena','Proteína, carbohidratos según carga y líquidos.']);else arr.push(['descanso','Baja revoluciones','No necesitas añadir otra sesión solo porque el día siga abierto.']);
 if(status?.football_override&&status?.football_time){const [hh,mm]=String(status.football_time).slice(0,5).split(':').map(Number),match=new Date();match.setHours(hh,mm,0,0);const d=(match-now)/36e5;if(d>0&&d<=2.2)arr.unshift(['prepartido','Preparación de partido',d<.7?'Empieza el calentamiento progresivo y bebe unos sorbos.':'Hidrátate y usa una ingesta fácil si tienes hambre; no pruebes alimentos nuevos.'])}
 const last=latest(data);if(last&&hoursAgo(last)<5&&rpe(last)>=7)arr.push(['post','Recuperación postentreno','Bebe, come con normalidad y no añadas intensidad solo por completar el día.']);if(m.sleepMin!=null&&m.sleepMin<390)arr.push(['sleep','Protege el descanso','La última noche fue corta. Prioriza dormir suficiente antes de otra sesión dura.']);return arr.slice(0,4).map(([code,title,text])=>({code,title,text,done:!!s[`${dayKey()}:${code}`]}))}
function renderAdvice(data){const page=document.getElementById('semana');if(!page)return;let hub=page.querySelector('.advice-hub');if(!hub){hub=document.createElement('div');hub.className='advice-hub';page.prepend(hub)}const m=model(data),cards=advice(data,m),todo=tasks(data,m),weekCount=data.activities.filter(a=>new Date(`${a.activity_date}T12:00:00`)>=monday()).length;hub.innerHTML=`<div class="sectionhead"><div><div class="eyebrow">Consejos</div><h1>Tu semana y lo que conviene hacer ahora</h1></div><span class="muted">${weekCount} actividades esta semana</span></div><section class="card advice-now"><div><span class="eyebrow">Qué toca ahora</span><h2>${esc(todo[0]?.title||'Sin tarea urgente')}</h2><p class="muted">Los checks confirman tareas pequeñas. Nunca crean un entrenamiento.</p></div><div class="advice-task-list">${todo.map(t=>`<label class="advice-task ${t.done?'is-done':''}"><input type="checkbox" data-advice-task="${esc(t.code)}" ${t.done?'checked':''}><span><b>${esc(t.title)}</b><small>${esc(t.text)}</small></span></label>`).join('')}</div></section><section class="card advice-week"><div class="advice-week-head"><div><span class="eyebrow">Semana real</span><h2>Actividad registrada</h2></div><div class="advice-status-mini"><span>Estado <b>${m.readiness}%</b></span><span>Piernas <b>${m.legs}%</b></span><span>Fatiga <b>${m.fatigue}/5</b></span></div></div><div class="advice-week-days">${week(data)}</div></section><div class="advice-grid">${cards.map(x=>`<article class="card advice-card"><i>${x.icon}</i><div><span class="eyebrow">${esc(x.title)}</span><p>${esc(x.text)}</p></div></article>`).join('')}</div>`;hub.querySelectorAll('[data-advice-task]').forEach(x=>x.onchange=()=>{taskSet(x.dataset.adviceTask,x.checked);x.closest('.advice-task').classList.toggle('is-done',x.checked)});const planner=page.querySelector('#plannerNotes')?.closest('.card');if(planner)planner.style.display='none';football(m)}
function football(m){const put=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};put('footballReadiness',`${m.readiness}%`);put('footballLegs',`${m.legs}%`);put('footballFatigue',`${m.fatigue}/5`);put('footballReadinessText',m.readiness>=72?'Carga reciente compatible con entrenar':m.readiness>=52?'Entrena con margen y reevalúa sensaciones':'Conviene priorizar recuperación')}
function body(){return`<svg class="state-body-svg" viewBox="0 0 240 520" role="img" aria-label="Mapa corporal de recuperación"><circle class="body-zone" data-zone="head" cx="120" cy="45" r="30"/><path class="body-zone" data-zone="torso" d="M82 88 Q120 70 158 88 L169 225 Q147 246 120 246 Q93 246 71 225Z"/><path class="body-zone" data-zone="armL" d="M75 96 Q56 100 43 124 L25 246 Q25 260 39 261 L57 151 L75 133Z"/><path class="body-zone" data-zone="armR" d="M165 96 Q184 100 197 124 L215 246 Q215 260 201 261 L183 151 L165 133Z"/><path class="body-zone" data-zone="core" d="M88 172 L152 172 L153 236 Q120 252 87 236Z"/><path class="body-zone" data-zone="quadL" d="M83 242 Q98 238 113 247 L107 365 L68 365Z"/><path class="body-zone" data-zone="quadR" d="M127 247 Q142 238 157 242 L172 365 L133 365Z"/><path class="body-zone" data-zone="calfL" d="M69 371 L107 371 L101 480 Q86 492 73 479Z"/><path class="body-zone" data-zone="calfR" d="M133 371 L171 371 L167 479 Q154 492 139 480Z"/><ellipse class="body-zone" data-zone="footL" cx="84" cy="494" rx="29" ry="12"/><ellipse class="body-zone" data-zone="footR" cx="156" cy="494" rx="29" ry="12"/></svg>`}
function latestAnalysis(data){return data.checkins?.find(x=>x.checkin_date===dayKey())?.answers?.state_analysis||data.checkins?.find(x=>x.answers?.state_analysis)?.answers?.state_analysis||null}
function loads(data,a){const z={head:0,torso:0,armL:0,armR:0,core:0,quadL:0,quadR:0,calfL:0,calfR:0,footL:0,footR:0};for(const x of data.activities){if(hoursAgo(x)>96)continue;const v=stress(x)/8,s=canonicalSport(x.activity_type);if(['football','futsal'].includes(s)){z.quadL+=v;z.quadR+=v;z.calfL+=v*.8;z.calfR+=v*.8;z.footL+=v*.5;z.footR+=v*.5;z.core+=v*.35}else if(s==='run'){z.quadL+=v*.8;z.quadR+=v*.8;z.calfL+=v;z.calfR+=v;z.footL+=v*.55;z.footR+=v*.55}else if(s==='cycling'){z.quadL+=v;z.quadR+=v;z.calfL+=v*.35;z.calfR+=v*.35}else if(s==='gym'){z.torso+=v*.7;z.armL+=v*.65;z.armR+=v*.65;z.core+=v*.5;z.quadL+=v*.45;z.quadR+=v*.45}}
 for(const x of a?.body_areas||[]){const v=(Number(x.severity)||3)*18,n=String(x.area),side=String(x.side),both=(l,r)=>{if(side==='izquierdo')z[l]=Math.max(z[l],v);else if(side==='derecho')z[r]=Math.max(z[r],v);else{z[l]=Math.max(z[l],v);z[r]=Math.max(z[r],v)}};if(/cuadriceps|isquios|rodilla|aductor|ingle|gluteo|cadera/.test(n))both('quadL','quadR');else if(/gemelo|tobillo/.test(n))both('calfL','calfR');else if(n==='pie')both('footL','footR');else if(/hombro|brazo|codo|muneca|mano/.test(n))both('armL','armR');else if(/pecho|espalda/.test(n))z.torso=Math.max(z.torso,v);else if(n==='core')z.core=Math.max(z.core,v)}return z}
const level=v=>v>=72?4:v>=48?3:v>=25?2:v>=10?1:0;
function result(a){const flags=a?.red_flags?.length?`<div class="state-flags">${a.red_flags.map(x=>`<p>⚠ ${esc(x)}</p>`).join('')}</div>`:'',tips=a?.advice?.length?`<ul>${a.advice.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';return`<div class="state-summary"><b>${esc(a?.summary||'Estado guardado')}</b><div><span>Energía ${a?.energy||'—'}/5</span><span>Fatiga ${a?.fatigue||'—'}/5</span><span>Carga muscular ${a?.soreness||'—'}/5</span></div>${flags}${tips}</div>`}
function statePage(){let p=document.getElementById('estado');if(!p){p=document.createElement('section');p.className='page';p.id='estado';document.getElementById('sueno')?.insertAdjacentElement('afterend',p)}return p}
function renderState(data){const page=statePage(),m=model(data),a=latestAnalysis(data),zone=loads(data,a);page.innerHTML=`<div class="sectionhead"><div><div class="eyebrow">Mi estado</div><h1>Cómo llegas hoy</h1><span class="muted">combina lo que cuentas con la carga de los días anteriores</span></div><div class="state-score-pill">${m.readiness}%</div></div><div class="state-grid"><section class="card state-body-card"><div><span class="eyebrow">Mapa corporal</span><h2>Recuperación estimada</h2><p class="muted">Más saturado = más carga o molestia registrada. Es contexto, no una medición fisiológica.</p></div><div class="state-body-wrap">${body()}<div class="state-legend"><span><i class="l0"></i>Fresco</span><span><i class="l2"></i>Carga</span><span><i class="l3"></i>Alto</span><span><i class="l4"></i>Molestia</span></div></div></section><section class="card state-note-card"><span class="eyebrow">¿Cómo te encuentras?</span><h2>Cuéntaselo a Training Lab</h2><p class="muted">Habla o escribe con naturalidad: “isquio derecho cargado, dormí bien, poca energía”.</p><div class="state-note-input"><textarea data-state-note rows="5" placeholder="Hoy me encuentro..."></textarea><button type="button" class="state-mic" data-state-mic aria-label="Dictar estado">🎙️</button></div><button type="button" class="btn" data-state-analyze>Analizar y guardar</button><div class="state-analysis-result">${a?result(a):'<p class="muted">Aún no has contado cómo te encuentras hoy.</p>'}</div></section></div><div class="state-metrics"><div class="card metric"><div class="k">Estado</div><div class="v">${m.readiness}%</div><div class="muted">carga + descanso reciente</div></div><div class="card metric"><div class="k">Piernas</div><div class="v">${m.legs}%</div><div class="muted">carga ponderada 96 h</div></div><div class="card metric"><div class="k">Fatiga</div><div class="v">${m.fatigue}/5</div><div class="muted">datos + nota de hoy</div></div></div><div data-injury-slot class="state-injury-slot"></div>`;for(const[k,v]of Object.entries(zone))page.querySelector(`[data-zone="${k}"]`)?.setAttribute('data-level',String(level(v)));const injury=document.getElementById('injuryArea')?.closest('.card');if(injury){injury.classList.add('state-injury-detail');page.querySelector('[data-injury-slot]')?.append(injury)}page.querySelector('[data-state-analyze]').onclick=()=>saveNote(page);page.querySelector('[data-state-mic]').onclick=()=>dictate(page);football(m)}
async function saveNote(page){const ta=page.querySelector('[data-state-note]'),btn=page.querySelector('[data-state-analyze]'),note=ta.value.trim();if(!note)return ta.focus();btn.disabled=true;btn.textContent='Analizando…';try{const out=await edge('analyze-state-note',{note});cache=null;ta.value='';page.querySelector('.state-analysis-result').innerHTML=result(out.analysis);await refresh(true)}catch(e){page.querySelector('.state-analysis-result').innerHTML=`<p class="warning">${esc(e?.message||e)}</p>`}finally{btn.disabled=false;btn.textContent='Analizar y guardar'}}
function dictate(page){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,btn=page.querySelector('[data-state-mic]'),ta=page.querySelector('[data-state-note]');if(!SR){ta.placeholder='El dictado no está disponible en este WebView. Puedes escribir aquí.';return ta.focus()}const r=new SR();r.lang='es-ES';r.interimResults=false;btn.classList.add('is-listening');btn.textContent='⏺';r.onresult=e=>{const t=[...e.results].map(x=>x[0]?.transcript||'').join(' ').trim();if(t)ta.value=(ta.value?ta.value+' ':'')+t};r.onend=()=>{btn.classList.remove('is-listening');btn.textContent='🎙️'};r.onerror=()=>{};r.start()}
async function refresh(force=false){const data=await load(force);if(!data)return;renderAdvice(data);renderState(data)}
function install(){css();let tries=0;const boot=()=>{if(document.getElementById('semana')&&document.getElementById('sueno'))refresh(false).catch(()=>{});else if(tries++<40)setTimeout(boot,200)};boot();document.addEventListener('click',e=>{if(e.target.closest?.('[data-page="semana"],[data-page="estado"],[data-page="futbol"]'))setTimeout(()=>refresh(true).catch(()=>{}),70)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>refresh(true).catch(()=>{}),150)})}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,0)}
