import {authState,canonicalSport,dayKey,edge,esc,finite,rest} from './training-data.js?v=20260911overhaul110';

const CSS='./advice-state.css?v=20260911overhaul110',TASK_KEY='traininglab-advice-checks-v1';
let cache=null,loading=false,lastLoad=0;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const defaults={football:8,futsal:8,run:5,cycling:4,gym:7,walk:2,other:4,recovery:2};
const legFactor={football:1,futsal:1,run:.88,cycling:.72,gym:.62,walk:.25,other:.3,recovery:.15};
const labelSport={football:'Fútbol',futsal:'Fútbol sala',run:'Running',cycling:'Ciclismo',gym:'Fuerza',walk:'Caminata',other:'Actividad'};
function ensureCss(){if(document.querySelector('link[data-advice-state]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.adviceState='1';document.head.append(l)}
function auth(){return authState()?.access_token}
function dateSince(days){const d=new Date();d.setDate(d.getDate()-days);return dayKey(d)}
async function load(force=false){if(loading)return cache;if(!force&&cache&&Date.now()-lastLoad<20000)return cache;if(!auth())return null;loading=true;try{
 const activities=await rest('activities',{select:'id,activity_date,started_at,activity_type,source,title,duration_min,moving_time_min,rpe,distance_km,avg_hr,max_hr,calories,high_intensity_m,metrics',activity_date:`gte.${dateSince(14)}`,order:'activity_date.desc,started_at.desc.nullslast',limit:80});
 const ids=(activities||[]).map(x=>x.id).filter(Boolean),analyses=ids.length?await rest('activity_analysis',{select:'activity_id,summary,report,hr_zones,speed_zones',activity_id:`in.(${ids.join(',')})`}):[];
 const [sleep,injuries,checkins,statuses]=await Promise.all([
  rest('sleep_records',{select:'sleep_date,sleep_start,sleep_end,total_sleep_min,deep_sleep_min,rem_sleep_min,light_sleep_min,awake_min,sleep_score,avg_hrv,resting_hr,metrics',sleep_date:`gte.${dateSince(9)}`,order:'sleep_date.desc',limit:14}).catch(()=>[]),
  rest('injuries',{select:'id,body_area,side,pain_score,status,trigger,advice,red_flags,updated_at',status:'eq.active',order:'updated_at.desc',limit:20}).catch(()=>[]),
  rest('daily_checkins',{select:'checkin_date,energy,soreness,stress,mood,motivation,sleep_quality,notes,answers,updated_at',checkin_date:`gte.${dateSince(14)}`,order:'checkin_date.desc',limit:20}).catch(()=>[]),
  rest('daily_status',{select:'day,fatigue,rest_requested,football_override,football_time,notes,updated_at',day:`gte.${dateSince(7)}`,order:'day.desc',limit:14}).catch(()=>[])
 ]);
 const amap=new Map((analyses||[]).map(x=>[String(x.activity_id),x]));cache={activities:(activities||[]).map(a=>({...a,analysis:amap.get(String(a.id))||null})),sleep:sleep||[],injuries:injuries||[],checkins:checkins||[],statuses:statuses||[]};lastLoad=Date.now();return cache
 }finally{loading=false}}
function activityDate(a){const d=a.started_at?new Date(a.started_at):new Date(`${a.activity_date}T12:00:00`);return Number.isNaN(+d)?null:d}
function hoursAgo(a){const d=activityDate(a);return d?Math.max(0,(Date.now()-d.getTime())/36e5):999}
function activityRpe(a){const v=Number(a.rpe);return v>0?v:(defaults[canonicalSport(a.activity_type)]||4)}
function stress(a){const dur=Math.max(0,Number(a.moving_time_min||a.duration_min)||0),age=hoursAgo(a),decay=Math.exp(-age/48);return dur*activityRpe(a)*decay}
function stateModel(data){
 const recent=(data?.activities||[]).filter(a=>hoursAgo(a)<=96),load=recent.reduce((s,a)=>s+stress(a),0),legLoad=recent.reduce((s,a)=>s+stress(a)*(legFactor[canonicalSport(a.activity_type)]??.4),0);
 const latestStatus=data?.statuses?.find(x=>x.day===dayKey()),latestCheck=data?.checkins?.find(x=>x.checkin_date===dayKey())||data?.checkins?.[0],fatigueManual=Number(latestStatus?.fatigue||latestCheck?.answers?.state_analysis?.fatigue||0);
 const sleep=data?.sleep?.[0],sleepMin=Number(sleep?.total_sleep_min)||null,sleepAdjust=sleepMin==null?0:clamp((sleepMin-420)/60,-1.2,1.2)*6;
 const fatigue=clamp(Math.round(fatigueManual||1+load/280),1,5),legs=Math.round(clamp(100-legLoad/8+sleepAdjust,18,100)),readiness=Math.round(clamp(100-load/11-(fatigue-1)*6+sleepAdjust,18,100));
 return{load,legLoad,fatigue,legs,readiness,sleepMin,latestCheck,latestStatus};
}
function weekStart(){const d=new Date(),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(0,0,0,0);return d}
function weekCards(data){const start=weekStart(),days=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dayKey(d),acts=(data.activities||[]).filter(a=>a.activity_date===key);days.push(`<div class="advice-day ${key===dayKey()?'is-today':''}"><span>${d.toLocaleDateString('es-ES',{weekday:'short'}).replace('.','')}</span><b>${d.getDate()}</b><div>${acts.map(a=>`<i title="${esc(labelSport[canonicalSport(a.activity_type)]||'Actividad')}">${sportEmoji(a.activity_type)}</i>`).join('')||'<small>·</small>'}</div></div>`)}return days.join('')}
function sportEmoji(type){return{football:'⚽',futsal:'⚽',run:'🏃',cycling:'🚴',gym:'🏋️',walk:'🚶'}[canonicalSport(type)]||'●'}
function latestRelevant(data){return [...(data.activities||[])].sort((a,b)=>(activityDate(b)?.getTime()||0)-(activityDate(a)?.getTime()||0))[0]||null}
function adviceFor(data,model){
 const last=latestRelevant(data),sport=canonicalSport(last?.activity_type),age=last?hoursAgo(last):999,hard=last&&activityRpe(last)>=7,inj=data.injuries||[],out=[];
 if(last&&age<30){const n=labelSport[sport]||'Actividad';out.push({icon:'♻️',title:'Recuperación',text:hard?`Vienes de ${n.toLowerCase()} exigente. Hoy prioriza movimiento suave, hidratación y una sesión fácil o descanso si las piernas siguen pesadas.`:`La última sesión fue ${n.toLowerCase()}. Mantén movimiento suave y observa cómo responden las piernas antes de añadir intensidad.`});}
 else out.push({icon:'♻️',title:'Recuperación',text:model.legs<55?'Las piernas siguen con carga acumulada de los últimos días. Evita juntar dos estímulos duros solo para completar volumen.':'La carga reciente permite entrenar, pero la sensación real manda si aparece dolor o fatiga inusual.'});
 const warm={football:'12–15 min: trote, movilidad dinámica, activación, progresiones y balón. Sin sprint máximo en frío.',futsal:'10–12 min: movilidad, cambios de dirección progresivos y aceleraciones cortas sin llegar al máximo.',run:'8–10 min: caminar/trote suave, tobillo-cadera y 3 progresiones cómodas antes de subir ritmo.',cycling:'5–8 min de pedaleo fácil antes de subir resistencia o potencia.',gym:'Haz 1–3 series de aproximación del primer ejercicio y aumenta carga gradualmente; no empieces con tu serie dura.'}[sport]||'Empieza con 5–10 min progresivos antes de cualquier trabajo intenso.';out.push({icon:'🔥',title:'Calentamiento',text:warm});
 const nutrition=hard&&age<8?'Tras una sesión exigente: comida normal con una fuente clara de proteína, carbohidratos suficientes y líquidos. No hace falta perseguir una ventana de minutos.':sport==='football'||sport==='futsal'?'En día de partido prioriza carbohidratos en las comidas previas y evita llegar con hambre; la proteína diaria sigue repartida durante el día.':'Reparte proteína durante el día y ajusta carbohidratos a la carga real, no al plan que finalmente no hayas hecho.';out.push({icon:'🍚',title:'Alimentación',text:nutrition});
 const sleep=model.sleepMin!=null&&model.sleepMin<420?'La última noche quedó por debajo de 7 h. No compenses con más intensidad: intenta proteger tu próxima ventana de sueño y usa una siesta corta solo si no desplaza todavía más tu horario.':'Mantén tu ventana habitual de sueño y juzga la recuperación por tendencia de varias noches, no por una sola cifra.';out.push({icon:'🌙',title:'Descanso',text:sleep});
 if(inj.length){const top=inj[0],pain=Number(top.pain_score)||0;out.push({icon:'🩹',title:'Molestias',text:`Hay una molestia activa en ${top.body_area}${top.side?' ('+top.side+')':''}${pain?' · '+pain+'/10':''}. Reduce la carga que la agrave; si aparecen señales de alarma o empeora claramente, busca valoración sanitaria.`})}else out.push({icon:'🩹',title:'Molestias',text:'No hay una lesión activa registrada. Si notas algo nuevo, cuéntalo en Mi estado para que el mapa corporal y los consejos lo incorporen.'});
 return out;
}
function taskState(){try{return JSON.parse(localStorage.getItem(TASK_KEY)||'{}')||{}}catch{return{}}}
function setTask(code,done){const s=taskState();s[`${dayKey()}:${code}`]=!!done;localStorage.setItem(TASK_KEY,JSON.stringify(s))}
function tasksFor(data,model){
 const s=taskState(),now=new Date(),h=now.getHours(),status=data.statuses?.find(x=>x.day===dayKey()),match=status?.football_override===true,statusTime=status?.football_time?String(status.football_time).slice(0,5):null,t=[];
 if(h>=12&&h<15)t.push(['desayuno','Haz tu primera comida completa','Come algo con proteína + carbohidratos y marca el check cuando esté hecho.']);else if(h>=15&&h<18)t.push(['comida','Comida principal','Repón energía con una comida completa; ajusta la cantidad a lo que has entrenado.']);else if(h>=18&&h<21)t.push(['merienda','Merienda','Si aún te queda actividad o faltan horas para cenar, una merienda útil evita llegar vacío.']);else if(h>=21||h<1)t.push(['cena','Cena','Cierra el día con proteína, carbohidratos según carga y líquidos.']);else t.push(['descanso','Baja revoluciones','No necesitas añadir otra sesión solo porque el día siga abierto.']);
 if(match&&statusTime){const [hh,mm]=statusTime.split(':').map(Number),m=new Date();m.setHours(hh,mm,0,0);const delta=(m-now)/36e5;if(delta>0&&delta<=2.2)t.unshift(['prepartido','Preparación de partido',delta<.7?'Empieza el calentamiento progresivo y bebe unos sorbos.':'Hidrátate y usa una ingesta fácil si tienes hambre; no pruebes alimentos nuevos.'])}
 const latest=latestRelevant(data);if(latest&&hoursAgo(latest)<5&&activityRpe(latest)>=7)t.push(['post','Recuperación postentreno','Bebe, come con normalidad y deja que la sesión cuente: hoy no hace falta sumar intensidad.']);
 if(model.sleepMin!=null&&model.sleepMin<390)t.push(['sleep','Protege el descanso','La última noche fue corta. Prioriza dormir suficiente antes de volver a meter intensidad.']);
 return t.slice(0,4).map(([code,title,text])=>({code,title,text,done:!!s[`${dayKey()}:${code}`]}))
}
function renderAdvice(data){const page=document.getElementById('semana');if(!page)return;let hub=page.querySelector('.advice-hub');if(!hub){hub=document.createElement('div');hub.className='advice-hub';page.prepend(hub)}const model=stateModel(data),adv=adviceFor(data,model),tasks=tasksFor(data,model),weekCount=(data.activities||[]).filter(a=>new Date(`${a.activity_date}T12:00:00`)>=weekStart()).length;hub.innerHTML=`<div class="sectionhead"><div><div class="eyebrow">Consejos</div><h1>Tu semana y lo que conviene hacer ahora</h1></div><span class="muted">${weekCount} actividades esta semana</span></div><section class="card advice-now"><div><span class="eyebrow">Qué toca ahora</span><h2>${tasks[0]?.title||'Sin tarea urgente'}</h2><p class="muted">Los checks confirman tareas pequeñas. Nunca crean un entrenamiento por sí solos.</p></div><div class="advice-task-list">${tasks.map(t=>`<label class="advice-task ${t.done?'is-done':''}"><input type="checkbox" data-advice-task="${esc(t.code)}" ${t.done?'checked':''}><span><b>${esc(t.title)}</b><small>${esc(t.text)}</small></span></label>`).join('')}</div></section><section class="card advice-week"><div class="advice-week-head"><div><span class="eyebrow">Semana real</span><h2>Actividad registrada</h2></div><div class="advice-status-mini"><span>Estado <b>${model.readiness}%</b></span><span>Piernas <b>${model.legs}%</b></span><span>Fatiga <b>${model.fatigue}/5</b></span></div></div><div class="advice-week-days">${weekCards(data)}</div></section><div class="advice-grid">${adv.map(x=>`<article class="card advice-card"><i>${x.icon}</i><div><span class="eyebrow">${esc(x.title)}</span><p>${esc(x.text)}</p></div></article>`).join('')}</div>`;hub.querySelectorAll('[data-advice-task]').forEach(x=>x.addEventListener('change',()=>{setTask(x.dataset.adviceTask,x.checked);x.closest('.advice-task').classList.toggle('is-done',x.checked)}));
 const planner=page.querySelector('#plannerNotes')?.closest('.card');if(planner)planner.style.display='none';updateFootballStatus(model)
}
function updateFootballStatus(model){const set=(id,text)=>{const e=document.getElementById(id);if(e)e.textContent=text};set('footballReadiness',`${model.readiness}%`);set('footballLegs',`${model.legs}%`);set('footballFatigue',`${model.fatigue}/5`);set('footballReadinessText',model.readiness>=72?'Carga reciente compatible con entrenar':model.readiness>=52?'Entrena con margen y reevalúa sensaciones':'Conviene priorizar recuperación')}
function bodySvg(){return`<svg class="state-body-svg" viewBox="0 0 240 520" role="img" aria-label="Mapa corporal de recuperación"><circle class="body-zone" data-zone="head" cx="120" cy="45" r="30"/><path class="body-zone" data-zone="torso" d="M82 88 Q120 70 158 88 L169 225 Q147 246 120 246 Q93 246 71 225Z"/><path class="body-zone" data-zone="armL" d="M75 96 Q56 100 43 124 L25 246 Q25 260 39 261 L57 151 L75 133Z"/><path class="body-zone" data-zone="armR" d="M165 96 Q184 100 197 124 L215 246 Q215 260 201 261 L183 151 L165 133Z"/><path class="body-zone" data-zone="core" d="M88 172 L152 172 L153 236 Q120 252 87 236Z"/><path class="body-zone" data-zone="quadL" d="M83 242 Q98 238 113 247 L107 365 L68 365Z"/><path class="body-zone" data-zone="quadR" d="M127 247 Q142 238 157 242 L172 365 L133 365Z"/><path class="body-zone" data-zone="calfL" d="M69 371 L107 371 L101 480 Q86 492 73 479Z"/><path class="body-zone" data-zone="calfR" d="M133 371 L171 371 L167 479 Q154 492 139 480Z"/><ellipse class="body-zone" data-zone="footL" cx="84" cy="494" rx="29" ry="12"/><ellipse class="body-zone" data-zone="footR" cx="156" cy="494" rx="29" ry="12"/></svg>`}
function regionLoads(data,analysis){const r={head:0,torso:0,armL:0,armR:0,core:0,quadL:0,quadR:0,calfL:0,calfR:0,footL:0,footR:0};for(const a of data.activities||[]){if(hoursAgo(a)>96)continue;const v=stress(a)/8,s=canonicalSport(a.activity_type);if(['football','futsal'].includes(s)){r.quadL+=v;r.quadR+=v;r.calfL+=v*.8;r.calfR+=v*.8;r.footL+=v*.5;r.footR+=v*.5;r.core+=v*.35}else if(s==='run'){r.quadL+=v*.8;r.quadR+=v*.8;r.calfL+=v;r.calfR+=v;r.footL+=v*.55;r.footR+=v*.55;r.core+=v*.25}else if(s==='cycling'){r.quadL+=v;r.quadR+=v;r.calfL+=v*.35;r.calfR+=v*.35;r.core+=v*.25}else if(s==='gym'){r.torso+=v*.7;r.armL+=v*.65;r.armR+=v*.65;r.core+=v*.5;r.quadL+=v*.45;r.quadR+=v*.45}}
 for(const a of analysis?.body_areas||[]){const sev=Number(a.severity)||3,val=sev*18,name=String(a.area),side=String(a.side);const add=(k)=>r[k]=Math.max(r[k],val);if(/cuadriceps|isquios|rodilla|aductor|ingle|gluteo|cadera/.test(name)){if(side==='izquierdo')add('quadL');else if(side==='derecho')add('quadR');else{add('quadL');add('quadR')}}else if(/gemelo|tobillo/.test(name)){if(side==='izquierdo')add('calfL');else if(side==='derecho')add('calfR');else{add('calfL');add('calfR')}}else if(name==='pie'){if(side==='izquierdo')add('footL');else if(side==='derecho')add('footR');else{add('footL');add('footR')}}else if(/hombro|brazo|codo|muneca|mano/.test(name)){if(side==='izquierdo')add('armL');else if(side==='derecho')add('armR');else{add('armL');add('armR')}}else if(/pecho|espalda/.test(name))add('torso');else if(/core/.test(name))add('core')}
 return r}
function zoneLevel(load){return load>=72?4:load>=48?3:load>=25?2:load>=10?1:0}
function latestStateAnalysis(data){return data.checkins?.find(x=>x.checkin_date===dayKey())?.answers?.state_analysis||data.checkins?.find(x=>x.answers?.state_analysis)?.answers?.state_analysis||null}
function ensureStatePage(){let p=document.getElementById('estado');if(!p){p=document.createElement('section');p.className='page';p.id='estado';document.getElementById('sueno')?.insertAdjacentElement('afterend',p)}return p}
function renderState(data){const page=ensureStatePage(),model=stateModel(data),analysis=latestStateAnalysis(data),loads=regionLoads(data,analysis);page.innerHTML=`<div class="sectionhead"><div><div class="eyebrow">Mi estado</div><h1>Cómo llegas hoy</h1><span class="muted">combina lo que cuentas con la carga de los días anteriores</span></div><div class="state-score-pill">${model.readiness}%</div></div><div class="state-grid"><section class="card state-body-card"><div><span class="eyebrow">Mapa corporal</span><h2>Recuperación estimada</h2><p class="muted">Más saturado = más carga o molestia registrada. Es una estimación de contexto, no una medición fisiológica.</p></div><div class="state-body-wrap">${bodySvg()}<div class="state-legend"><span><i class="l0"></i>Fresco</span><span><i class="l2"></i>Carga</span><span><i class="l3"></i>Alto</span><span><i class="l4"></i>Molestia</span></div></div></section><section class="card state-note-card"><span class="eyebrow">¿Cómo te encuentras?</span><h2>Cuéntaselo a Training Lab</h2><p class="muted">Habla o escribe con naturalidad: “isquio derecho cargado, dormí bien, poca energía”. Se guarda como tu estado de hoy.</p><div class="state-note-input"><textarea data-state-note rows="5" placeholder="Hoy me encuentro..."></textarea><button type="button" class="state-mic" data-state-mic aria-label="Dictar estado">🎙️</button></div><button type="button" class="btn" data-state-analyze>Analizar y guardar</button><div class="state-analysis-result">${analysis?stateResult(analysis):'<p class="muted">Aún no has contado cómo te encuentras hoy.</p>'}</div></section></div><div class="state-metrics"><div class="card metric"><div class="k">Estado</div><div class="v">${model.readiness}%</div><div class="muted">carga + descanso reciente</div></div><div class="card metric"><div class="k">Piernas</div><div class="v">${model.legs}%</div><div class="muted">carga ponderada 96 h</div></div><div class="card metric"><div class="k">Fatiga</div><div class="v">${model.fatigue}/5</div><div class="muted">datos + nota de hoy</div></div></div><div data-injury-slot class="state-injury-slot"></div>`;
 Object.entries(loads).forEach(([k,v])=>page.querySelector(`[data-zone="${k}"]`)?.setAttribute('data-level',String(zoneLevel(v))));
 const injury=document.getElementById('injuryArea')?.closest('.card');if(injury){const slot=page.querySelector('[data-injury-slot]');injury.classList.add('state-injury-detail');slot.append(injury)}
 page.querySelector('[data-state-analyze]')?.addEventListener('click',()=>saveStateNote(page));page.querySelector('[data-state-mic]')?.addEventListener('click',()=>dictate(page));updateFootballStatus(model)
}
function stateResult(a){const flags=Array.isArray(a.red_flags)&&a.red_flags.length?`<div class="state-flags">${a.red_flags.map(x=>`<p>⚠ ${esc(x)}</p>`).join('')}</div>`:'',advice=Array.isArray(a.advice)&&a.advice.length?`<ul>${a.advice.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';return`<div class="state-summary"><b>${esc(a.summary||'Estado guardado')}</b><div><span>Energía ${a.energy||'—'}/5</span><span>Fatiga ${a.fatigue||'—'}/5</span><span>Carga muscular ${a.soreness||'—'}/5</span></div>${flags}${advice}</div>`}
async function saveStateNote(page){const textarea=page.querySelector('[data-state-note]'),button=page.querySelector('[data-state-analyze]'),note=textarea?.value?.trim();if(!note){textarea?.focus();return}button.disabled=true;button.textContent='Analizando…';try{const out=await edge('analyze-state-note',{note});cache=null;await refresh(true);textarea.value='';const result=page.querySelector('.state-analysis-result');if(result)result.innerHTML=stateResult(out.analysis||{});}catch(e){const result=page.querySelector('.state-analysis-result');if(result)result.innerHTML=`<p class="warning">${esc(e?.message||e)}</p>`}finally{button.disabled=false;button.textContent='Analizar y guardar'}}
function dictate(page){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,btn=page.querySelector('[data-state-mic]'),textarea=page.querySelector('[data-state-note]');if(!SR){textarea.placeholder='El dictado no está disponible en este WebView. Puedes escribir aquí cómo te encuentras.';textarea.focus();return}const r=new SR();r.lang='es-ES';r.interimResults=false;r.continuous=false;btn.classList.add('is-listening');btn.textContent='⏺';r.onresult=e=>{const text=[...e.results].map(x=>x[0]?.transcript||'').join(' ').trim();if(text)textarea.value=(textarea.value?textarea.value+' ':'')+text};r.onerror=()=>{};r.onend=()=>{btn.classList.remove('is-listening');btn.textContent='🎙️'};r.start()}
async function refresh(force=false){const data=await load(force);if(!data)return;renderAdvice(data);renderState(data)}
function install(){ensureCss();let tries=0;const boot=async()=>{if(document.getElementById('semana')&&document.getElementById('sueno')){await refresh(false).catch(()=>{});return}if(tries++<40)setTimeout(boot,200)};boot();document.addEventListener('click',e=>{if(e.target.closest?.('[data-page="semana"],[data-page="estado"],[data-page="futbol"]'))setTimeout(()=>refresh(true).catch(()=>{}),70)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>refresh(true).catch(()=>{}),150)})}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,0)}
