const CSS='./coros-design.css?v=20260911coros101';
const rowCache=new Map();
let installed=false,feedObserver=null,openWrapped=false;
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function ensureCss(){if(document.querySelector('link[data-coros-design]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.corosDesign='1';document.head.append(l)}
function authState(){try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('sb-')||!key.endsWith('-auth-token'))continue;const parsed=JSON.parse(localStorage.getItem(key)||'null');if(parsed?.access_token&&String(key).includes('nnpvklaxhomarxszlclt'))return parsed}}catch{}return null}
async function restRows(ids){const missing=[...new Set(ids.map(String).filter(id=>id&&!rowCache.has(id)))];if(!missing.length)return;const auth=authState(),cfg=window.TrainingLab?.config;if(!auth?.access_token||!cfg?.url||!cfg?.key)return;const url=new URL(`${cfg.url}/rest/v1/activities`);url.searchParams.set('select','id,title,source,activity_type,started_at,activity_date,duration_min,moving_time_min,distance_km,avg_hr,max_hr,top_speed_kmh,avg_pace_sec_km');url.searchParams.set('id',`in.(${missing.join(',')})`);try{const request=window.TrainingLab?.request||fetch;const response=await request(url.href,{headers:{apikey:cfg.key,Authorization:`Bearer ${auth.access_token}`,Accept:'application/json'},cache:'no-store'});if(!response.ok)return;const rows=await response.json();for(const row of Array.isArray(rows)?rows:[])rowCache.set(String(row.id),row)}catch{}}
function sourceLabel(source){const s=String(source||'').toLowerCase();if(s.includes('fit'))return 'FIT';if(s.includes('health'))return 'Health Connect';if(s.includes('manual'))return 'Manual';return source?String(source):''}
function formatDate(row){const raw=row?.started_at||row?.activity_date;if(!raw)return '';const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(String(raw))?`${raw}T12:00:00`:raw);if(Number.isNaN(d.getTime()))return '';return d.toLocaleString('es-ES',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function formatPace(sec){if(!finite(sec))return '—';const n=Math.round(Number(sec)),m=Math.floor(n/60),s=n%60;return `${m}'${String(s).padStart(2,'0')}"/km`}
function enrichCard(card,row){if(!card||!row)return;const copy=card.querySelector('.activity-copy');if(!copy)return;let title=copy.querySelector('.coros-activity-title');if(!title){title=document.createElement('span');title.className='coros-activity-title';copy.append(title)}title.textContent=row.title&&row.title!=='Health Connect'?row.title:(row.activity_type==='cycling'?'Ciclismo':row.activity_type==='run'?'Carrera':row.activity_type==='gym'?'Fuerza':row.activity_type==='futsal'?'Fútbol sala':'Fútbol');const label=sourceLabel(row.source);let source=copy.querySelector('.coros-source-pill');if(label){if(!source){source=document.createElement('span');source.className='coros-source-pill';copy.append(source)}source.textContent=label}else source?.remove()}
async function enrichVisibleCards(){const cards=[...document.querySelectorAll('#homeActivityFeed .activity-card[data-activity-id]')];if(!cards.length)return;await restRows(cards.map(c=>c.dataset.activityId));for(const card of cards)enrichCard(card,rowCache.get(String(card.dataset.activityId)))}
function decorateChartStats(detail,row){if(!detail||!row)return;const add=(selector,stats)=>{const title=detail.querySelector(`${selector} .activity-section-title`);if(!title||title.querySelector('.coros-chart-stats')||!stats.length)return;const box=document.createElement('div');box.className='coros-chart-stats';box.innerHTML=stats.map(([k,v])=>`<span>${esc(k)} <strong>${esc(v)}</strong></span>`).join('');title.append(box)};if(finite(row.avg_hr)||finite(row.max_hr))add('[data-analysis-block="hr"]',[[finite(row.max_hr)?'Máx':null,finite(row.max_hr)?Math.round(row.max_hr):null],[finite(row.avg_hr)?'Media':null,finite(row.avg_hr)?Math.round(row.avg_hr):null]].filter(x=>x[0]));if(row.activity_type==='run'){if(finite(row.avg_pace_sec_km))add('[data-analysis-block="effort"]',[['Media',formatPace(row.avg_pace_sec_km)]])}else{const moving=Number(row.moving_time_min||row.duration_min),avg=finite(row.distance_km)&&moving>0?Number(row.distance_km)/(moving/60):null;const stats=[];if(finite(row.top_speed_kmh))stats.push(['Mejor',`${Number(row.top_speed_kmh).toFixed(1)}`]);if(finite(avg))stats.push(['Media',`${avg.toFixed(1)}`]);add('[data-analysis-block="effort"]',stats)}}
function decorateDetail(row){const detail=document.getElementById('activityDetailView');if(!detail||detail.hidden||!row)return;const h=detail.querySelector('.activity-detail-header'),h1=h?.querySelector('h1'),p=h?.querySelector('p'),back=detail.querySelector('.activity-detail-back');if(back)back.setAttribute('aria-label','Volver a actividades');if(h1&&row.title&&row.title!=='Health Connect')h1.textContent=row.title;if(p){const text=formatDate(row);if(text)p.textContent=text}if(h&&!h.querySelector('.coros-detail-source')){const label=sourceLabel(row.source);if(label){const s=document.createElement('span');s.className='coros-detail-source';s.textContent=label;h.append(s)}}decorateChartStats(detail,row)}
async function onDetailOpen(id){await restRows([id]);const row=rowCache.get(String(id));if(!row)return;decorateDetail(row);for(const delay of [180,500,1100])setTimeout(()=>{const d=document.getElementById('activityDetailView');if(d&&!d.hidden)decorateDetail(row)},delay)}
function wrapDetail(){if(openWrapped||typeof window.openActivityDetail!=='function')return false;openWrapped=true;const original=window.openActivityDetail;window.openActivityDetail=function(activityId){const result=original.apply(this,arguments);queueMicrotask(()=>onDetailOpen(activityId));return result};return true}
function install(){if(installed)return;installed=true;ensureCss();const feed=document.getElementById('homeActivityFeed');if(feed){feedObserver=new MutationObserver(()=>queueMicrotask(enrichVisibleCards));feedObserver.observe(feed,{childList:true});queueMicrotask(enrichVisibleCards)}let tries=0;const timer=setInterval(()=>{if(wrapDetail()||tries++>30)clearInterval(timer)},50)}
if(typeof window!=='undefined'&&typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install()}
