import {NUTRITION_PRESETS,kcalFor} from './nutrition-tracker.js?v=20260911food103';

const CSS_URL='./food-camera.css?v=20260911food104';
const ENDPOINT='analyze-food-image';
let installed=false,input=null,observer=null,previewUrl=null,busy=false;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
export function defaultMealType(hour=new Date().getHours()){
  const h=Number(hour);
  if(h>=13&&h<15)return'desayuno';
  if(h>=15&&h<18)return'comida';
  if(h>=18&&h<21)return'merienda';
  if(h>=21||h<1)return'cena';
  return'recena';
}
export function validateFoodAnalysis(raw={}){
  const portion=['small','normal','large'].includes(raw.portion)?raw.portion:'normal';
  const ingredients=Array.isArray(raw.ingredients)?raw.ingredients.map(x=>String(x||'').trim()).filter(Boolean).slice(0,10):[];
  return{
    is_food:raw.is_food!==false,
    dish_name:String(raw.dish_name||'Plato sin identificar').trim().slice(0,120),
    preset_id:String(raw.preset_id||'none'),
    confidence:clamp(raw.confidence,0,1),
    preset_confidence:clamp(raw.preset_confidence,0,1),
    portion,
    ingredients,
    protein_g:Math.round(clamp(raw.protein_g,0,220)),
    carbs_g:Math.round(clamp(raw.carbs_g,0,350)),
    fat_g:Math.round(clamp(raw.fat_g,0,220)),
    macro_source:raw.macro_source==='preset'?'preset':'visual_estimate',
    notes:String(raw.notes||'').trim().slice(0,280)
  };
}
export function presetById(id){for(const group of Object.values(NUTRITION_PRESETS))for(const item of group)if(item.id===id)return item;return null}
export function resolvedMacros(raw={}){
  const value=validateFoodAnalysis(raw),preset=value.preset_confidence>=.75?presetById(value.preset_id):null;
  if(preset)return{...value,dish_name:preset.title,protein_g:preset.protein,carbs_g:preset.carbs,fat_g:preset.fat,macro_source:'preset'};
  return value;
}
function ensureCss(){if(document.querySelector('link[data-food-camera-css]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=CSS_URL;link.dataset.foodCameraCss='1';document.head.append(link)}
function authState(){try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('sb-')||!key.endsWith('-auth-token'))continue;const parsed=JSON.parse(localStorage.getItem(key)||'null');if(parsed?.access_token)return parsed}}catch{}return null}
function userId(auth){if(auth?.user?.id)return auth.user.id;try{const part=String(auth?.access_token||'').split('.')[1]||'',pad=part+'='.repeat((4-part.length%4)%4),payload=JSON.parse(atob(pad.replace(/-/g,'+').replace(/_/g,'/')));return payload?.sub||null}catch{return null}}
function ensureInput(){if(input)return input;input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/heic,image/heif';input.setAttribute('capture','environment');input.hidden=true;input.dataset.foodCameraInput='1';input.addEventListener('change',()=>{const file=input.files?.[0];input.value='';if(file)analyzeFile(file)});document.body.append(input);return input}
function mountLauncher(){const root=document.querySelector('.nutrition-tracker-root');if(!root)return false;if(root.querySelector('[data-food-camera-launcher]'))return true;const title=root.querySelector('.nutrition-title'),card=document.createElement('section');card.className='food-camera-launcher';card.dataset.foodCameraLauncher='1';card.innerHTML=`<button type="button" class="food-camera-main" data-food-camera-open><span class="food-camera-icon">⌾</span><span><b>Añadir plato con foto</b><small>Haz una foto y la IA estima el plato y sus macros</small></span><i>›</i></button>`;card.querySelector('[data-food-camera-open]').addEventListener('click',()=>{if(!authState()?.access_token){showMessage('Inicia sesión para usar el reconocimiento por IA.');return}ensureInput().click()});if(title)title.after(card);else root.prepend(card);return true}
function install(){if(installed)return;ensureCss();ensureInput();let tries=0;const wait=()=>{const root=document.querySelector('.nutrition-tracker-root');if(root){installed=true;mountLauncher();observer=new MutationObserver(()=>{if(!document.querySelector('.nutrition-tracker-root [data-food-camera-launcher]'))queueMicrotask(mountLauncher)});observer.observe(root,{childList:true,subtree:false});return}if(tries++<80)setTimeout(wait,150)};wait()}
function closeModal(){document.querySelector('.food-camera-modal')?.remove();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}}
function modalShell(content){document.querySelector('.food-camera-modal')?.remove();const overlay=document.createElement('div');overlay.className='food-camera-modal';overlay.innerHTML=`<div class="food-camera-sheet"><button class="food-camera-close" type="button" aria-label="Cerrar">×</button>${content}</div>`;overlay.querySelector('.food-camera-close').onclick=closeModal;overlay.addEventListener('click',e=>{if(e.target===overlay&&!busy)closeModal()});document.body.append(overlay);return overlay}
function showMessage(message,error=true){const modal=modalShell(`<div class="food-camera-state ${error?'is-error':''}"><div class="food-camera-state-icon">${error?'!':'✓'}</div><h2>${error?'No se pudo analizar':'Listo'}</h2><p>${esc(message)}</p><button class="btn alt" type="button" data-food-close>Cerrar</button></div>`);modal.querySelector('[data-food-close]').onclick=closeModal}
function loadingModal(url){return modalShell(`<div class="food-camera-loading"><img src="${esc(url)}" alt="Foto del plato"><div class="food-camera-scan"></div><div class="food-camera-thinking"><span></span><div><b>Reconociendo el plato…</b><small>Buscando ingredientes, ración y coincidencias con tus comidas habituales</small></div></div></div>`)}
async function imageToJpeg(file,maxSide=1280,quality=.82){
  if(!file?.type?.startsWith('image/'))throw new Error('Selecciona una imagen.');
  const objectUrl=URL.createObjectURL(file);let img;
  try{img=await new Promise((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=()=>reject(new Error('No se puede leer esta imagen.'));el.src=objectUrl});const scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d',{alpha:false}).drawImage(img,0,0,w,h);const blob=await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error('No se pudo preparar la foto.')),'image/jpeg',quality));if(blob.size>3_500_000)throw new Error('La foto sigue siendo demasiado grande. Acércate al plato y vuelve a intentarlo.');const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(new Error('No se pudo leer la foto.'));r.readAsDataURL(blob)});return{base64,mimeType:'image/jpeg',blob}}finally{URL.revokeObjectURL(objectUrl)}}
async function callAi(image){const cfg=window.TrainingLab?.config,auth=authState();if(!cfg?.url||!cfg?.key||!auth?.access_token)throw new Error('Inicia sesión para usar el reconocimiento.');const runner=window.TrainingLab?.request||fetch,res=await runner(`${cfg.url}/functions/v1/${ENDPOINT}`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${auth.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({image_base64:image.base64,mime_type:image.mimeType,meal_hint:defaultMealType()}),cache:'no-store'}),payload=await res.json().catch(()=>({}));if(!res.ok){if(payload?.code==='gemini_not_configured')throw new Error('El reconocimiento está instalado, pero falta configurar la clave GEMINI_API_KEY en Supabase.');throw new Error(payload?.error||`Error de reconocimiento (${res.status}).`)}return resolvedMacros(payload)}
async function analyzeFile(file){if(busy)return;busy=true;try{const prepared=await imageToJpeg(file);previewUrl=URL.createObjectURL(prepared.blob);loadingModal(previewUrl);const analysis=await callAi(prepared);if(!analysis.is_food){showMessage('La IA no ve un plato de comida con suficiente claridad. Haz la foto más cerca y con buena luz.');return}showResult(analysis)}catch(e){showMessage(e instanceof Error?e.message:String(e))}finally{busy=false}}
function mealOptions(selected){return[['desayuno','Desayuno'],['comida','Comida'],['merienda','Merienda'],['cena','Cena'],['recena','Recena'],['picoteo','Picoteo']].map(([v,l])=>`<option value="${v}" ${v===selected?'selected':''}>${l}</option>`).join('')}
function showResult(a){const confidence=Math.round(a.confidence*100),source=a.macro_source==='preset'?'Coincide con un plato habitual':'Estimación visual',ingredients=a.ingredients.length?`<div class="food-camera-ingredients">${a.ingredients.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:'',modal=modalShell(`<div class="food-camera-result"><div class="food-camera-photo"><img src="${esc(previewUrl||'')}" alt="Plato analizado"><span>${confidence}% confianza</span></div><div class="food-camera-result-head"><span class="food-camera-source ${a.macro_source==='preset'?'is-preset':''}">${source}</span><h2>${esc(a.dish_name)}</h2>${ingredients}${a.notes?`<p>${esc(a.notes)}</p>`:''}</div><div class="food-camera-fields"><label>Tipo de comida<select data-ai-meal-type>${mealOptions(defaultMealType())}</select></label><label class="food-camera-name">Nombre<input data-ai-title value="${esc(a.dish_name)}" maxlength="120"></label><label>Proteína<input type="number" min="0" max="220" step="1" data-ai-protein value="${a.protein_g}"><small>g</small></label><label>Carbohidratos<input type="number" min="0" max="350" step="1" data-ai-carbs value="${a.carbs_g}"><small>g</small></label><label>Grasas<input type="number" min="0" max="220" step="1" data-ai-fat value="${a.fat_g}"><small>g</small></label></div><div class="food-camera-kcal">≈ <b data-ai-kcal>${kcalFor({protein:a.protein_g,carbs:a.carbs_g,fat:a.fat_g})}</b> kcal <span>· puedes corregir los macros antes de añadir</span></div><button class="food-camera-add btn" type="button" data-ai-add>Añadir al día</button></div>`);const updateKcal=()=>{const p=Number(modal.querySelector('[data-ai-protein]').value)||0,c=Number(modal.querySelector('[data-ai-carbs]').value)||0,f=Number(modal.querySelector('[data-ai-fat]').value)||0;modal.querySelector('[data-ai-kcal]').textContent=kcalFor({protein:p,carbs:c,fat:f})};modal.querySelectorAll('[data-ai-protein],[data-ai-carbs],[data-ai-fat]').forEach(x=>x.addEventListener('input',updateKcal));modal.querySelector('[data-ai-add]').onclick=()=>saveResult(modal)}
async function saveResult(modal){if(busy)return;const cfg=window.TrainingLab?.config,auth=authState(),uid=userId(auth);if(!cfg?.url||!cfg?.key||!auth?.access_token||!uid){showMessage('Inicia sesión para guardar el plato.');return}const title=modal.querySelector('[data-ai-title]').value.trim(),mealType=modal.querySelector('[data-ai-meal-type]').value,protein=Math.round(clamp(modal.querySelector('[data-ai-protein]').value,0,220)),carbs=Math.round(clamp(modal.querySelector('[data-ai-carbs]').value,0,350)),fat=Math.round(clamp(modal.querySelector('[data-ai-fat]').value,0,220));if(!title){showMessage('Pon un nombre al plato.');return}busy=true;const btn=modal.querySelector('[data-ai-add]');btn.disabled=true;btn.textContent='Añadiendo…';try{const runner=window.TrainingLab?.request||fetch,res=await runner(`${cfg.url}/rest/v1/meal_logs?select=id,eaten_at,meal_type,title,protein_g,carbs_g,fat_g`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${auth.access_token}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({user_id:uid,meal_type:mealType,title,protein_g:protein,carbs_g:carbs,fat_g:fat,eaten_at:new Date().toISOString()}),cache:'no-store'});if(!res.ok)throw new Error(`No se pudo guardar (${res.status})`);const rows=await res.json(),row=Array.isArray(rows)?rows[0]:null;if(row){window.cloudMeals=window.cloudMeals||[];window.cloudMeals.unshift(row)}closeModal();document.dispatchEvent(new Event('visibilitychange'));showTinyToast(`Añadido: ${title}`)}catch(e){btn.disabled=false;btn.textContent='Añadir al día';showMessage(e instanceof Error?e.message:String(e))}finally{busy=false}}
function showTinyToast(text){let t=document.querySelector('.food-camera-toast');if(!t){t=document.createElement('div');t.className='food-camera-toast';document.body.append(t)}t.textContent=text;t.classList.add('show');clearTimeout(showTinyToast.timer);showTinyToast.timer=setTimeout(()=>t.classList.remove('show'),1800)}

if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else queueMicrotask(install)}
