export const NUTRITION_PRESETS={
 breakfast:[
  {id:'yogur_cereales',title:'Yogur + cereales + crema de cacahuete desgrasada + arándanos y frambuesas',protein:22,carbs:68,fat:10},
  {id:'batido_proteina',title:'Batido de proteína (30 g) + plátano + crema de cacahuete',protein:36,carbs:42,fat:12},
  {id:'sandwich_atun_huevo',title:'Sándwich de atún + huevo duro',protein:38,carbs:42,fat:11}
 ],
 comida:[
  {id:'ensalada_pasta_atun',title:'Ensalada de pasta con atún',protein:38,carbs:80,fat:15},
  {id:'arroz_carne_huevo',title:'Arroz blanco con carne y huevo',protein:42,carbs:85,fat:23},
  {id:'arroz_atun_huevo',title:'Arroz blanco con atún y huevo',protein:38,carbs:85,fat:15},
  {id:'arroz_pescado_huevo',title:'Arroz blanco con pescado y huevo',protein:42,carbs:85,fat:13},
  {id:'pasta_atun',title:'Pasta con atún',protein:38,carbs:82,fat:10},
  {id:'carne_patatas',title:'Carne con patatas',protein:40,carbs:60,fat:24},
  {id:'tortilla_patatas',title:'Tortilla de patatas',protein:25,carbs:55,fat:30},
  {id:'huevos_rotos',title:'Huevos rotos',protein:24,carbs:65,fat:32},
  {id:'sopa_fideos',title:'Sopa con fideos',protein:15,carbs:55,fat:10}
 ],
 cena:[
  {id:'ensalada_pasta_atun',title:'Ensalada de pasta con atún',protein:38,carbs:80,fat:15},
  {id:'arroz_carne_huevo',title:'Arroz blanco con carne y huevo',protein:42,carbs:85,fat:23},
  {id:'arroz_atun_huevo',title:'Arroz blanco con atún y huevo',protein:38,carbs:85,fat:15},
  {id:'arroz_pescado_huevo',title:'Arroz blanco con pescado y huevo',protein:42,carbs:85,fat:13},
  {id:'pasta_atun',title:'Pasta con atún',protein:38,carbs:82,fat:10},
  {id:'carne_patatas',title:'Carne con patatas',protein:40,carbs:60,fat:24},
  {id:'tortilla_patatas',title:'Tortilla de patatas',protein:25,carbs:55,fat:30},
  {id:'huevos_rotos',title:'Huevos rotos',protein:24,carbs:65,fat:32},
  {id:'sopa_fideos',title:'Sopa con fideos',protein:15,carbs:55,fat:10},
  {id:'bocadillo',title:'Bocadillo',protein:30,carbs:70,fat:18},
  {id:'tapas_bravas',title:'Tapas variadas + bravas',protein:25,carbs:80,fat:35},
  {id:'pizza',title:'Pizza',protein:35,carbs:105,fat:35},
  {id:'hamburguesa_patatas',title:'Hamburguesa con patatas',protein:40,carbs:80,fat:38}
 ],
 picoteo:[
  {id:'nueces',title:'Nueces (30 g)',protein:6,carbs:6,fat:18},
  {id:'gazpacho',title:'Gazpacho (vaso grande)',protein:3,carbs:14,fat:8},
  {id:'queso',title:'Queso (ración ~60 g)',protein:15,carbs:1,fat:18}
 ]
};
const LABELS={breakfast:'Desayuno / recena',comida:'Comida',merienda:'Merienda',cena:'Cena',picoteo:'Picoteo'};
const DEFAULT_TARGETS={protein:130,carbs:330,fat:75},LOCAL_KEY='traininglab-nutrition-local-v1';
let root=null,entries=[],busy=false,breakfastMode='desayuno',openOther=null,draft=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const round=v=>Math.max(0,Math.round(Number(v)||0));
export const kcalFor=m=>Math.round(Number(m.protein||0)*4+Number(m.carbs||0)*4+Number(m.fat||0)*9);
export function calculateNutritionTotals(items=[]){return items.reduce((a,x)=>({protein:a.protein+Number(x.protein_g??x.protein??0),carbs:a.carbs+Number(x.carbs_g??x.carbs??0),fat:a.fat+Number(x.fat_g??x.fat??0)}),{protein:0,carbs:0,fat:0})}
export function parseNutritionTargets(text='',fallback=DEFAULT_TARGETS){const s=String(text),p=s.match(/prote[ií]na\s+\d+(?:[.,]\d+)?\s*\/\s*(\d+(?:[.,]\d+)?)/i),c=s.match(/(?:HC|carbohidratos?)\s+\d+(?:[.,]\d+)?\s*\/\s*(\d+(?:[.,]\d+)?)/i),f=s.match(/grasas?\s+\d+(?:[.,]\d+)?\s*\/\s*(\d+(?:[.,]\d+)?)/i);return{protein:p?Number(p[1].replace(',','.')):fallback.protein,carbs:c?Number(c[1].replace(',','.')):fallback.carbs,fat:f?Number(f[1].replace(',','.')):fallback.fat}}
const DIRECT=[
 [/pizza/,{protein:35,carbs:105,fat:35}],[/hamburgues/,{protein:35,carbs:42,fat:25}],[/paella/,{protein:30,carbs:85,fat:20}],[/sushi/,{protein:30,carbs:90,fat:15}],[/kebab|durum/,{protein:35,carbs:65,fat:25}],[/ramen/,{protein:30,carbs:75,fat:20}],[/burrito/,{protein:35,carbs:75,fat:22}],[/tortilla.*patat/,{protein:25,carbs:55,fat:30}],[/huevos? rotos/,{protein:24,carbs:65,fat:32}]
];
const PARTS=[
 [/arroz/,{protein:6,carbs:70,fat:1}],[/pasta|espagueti|macarron/,{protein:10,carbs:75,fat:2}],[/patat/,{protein:5,carbs:50,fat:8}],[/pan|bocadillo|sandwich|tostad/,{protein:8,carbs:55,fat:4}],[/fideo|noodle/,{protein:8,carbs:55,fat:2}],[/pollo|pavo/,{protein:32,carbs:0,fat:7}],[/carne|ternera|cerdo|filete/,{protein:30,carbs:0,fat:15}],[/atun/,{protein:25,carbs:0,fat:3}],[/salmon/,{protein:30,carbs:0,fat:18}],[/pescad|merluza|bacalao/,{protein:30,carbs:0,fat:8}],[/huevo/,{protein:12,carbs:1,fat:10}],[/queso/,{protein:15,carbs:1,fat:18}],[/lentej|garbanz|alubia|legumbre/,{protein:18,carbs:50,fat:4}],[/ensalada|verdura|hortaliza/,{protein:3,carbs:15,fat:5}],[/mayonesa|alioli|salsa cremosa/,{protein:0,carbs:5,fat:12}],[/frut|platano/,{protein:1,carbs:25,fat:0}],[/yogur|skyr/,{protein:12,carbs:10,fat:4}]
];
const GENERIC={breakfast:{protein:20,carbs:45,fat:15},merienda:{protein:18,carbs:40,fat:12},picoteo:{protein:8,carbs:15,fat:12},comida:{protein:30,carbs:65,fat:25},cena:{protein:30,carbs:65,fat:25}};
export function estimateOtherMeal(description,category='comida',portion='normal'){
 const text=norm(description),factor=portion==='pequena'?.75:portion==='grande'?1.25:1;let result=null,recognized=false;
 for(const [re,m] of DIRECT)if(re.test(text)){result={...m};recognized=true;break}
 if(!result){let protein=0,carbs=0,fat=0,hits=0;for(const [re,m] of PARTS)if(re.test(text)){protein+=m.protein;carbs+=m.carbs;fat+=m.fat;hits++}if(/frit|rebozad|empanad/.test(text)){carbs+=10;fat+=12;hits++}if(/patat/.test(text)&&/frit|brava/.test(text))fat+=12;recognized=hits>0;result=recognized?{protein,carbs,fat}:{...(GENERIC[category]||GENERIC.comida)}}
 if(/hamburgues/.test(text)&&/patat/.test(text)){result={protein:40,carbs:80,fat:38};recognized=true}if(/tapas|bravas/.test(text)){result={protein:25,carbs:80,fat:35};recognized=true}
 return{protein:round(result.protein*factor),carbs:round(result.carbs*factor),fat:round(result.fat*factor),portion,fallback:!recognized};
}
function ensureCss(){if(document.querySelector('link[data-nutrition-tracker-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./nutrition-tracker.css?v=20260911food103';l.dataset.nutritionTrackerCss='1';document.head.append(l)}
function authState(){try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('sb-')||!k.endsWith('-auth-token'))continue;const a=JSON.parse(localStorage.getItem(k)||'null');if(a?.access_token)return a}}catch{}return null}
function jwtSub(token=''){try{let s=String(token).split('.')[1].replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return JSON.parse(atob(s))?.sub||null}catch{return null}}
function uid(a){return a?.user?.id||jwtSub(a?.access_token)||null}
function dayKey(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function today(iso){const d=new Date(iso);return!Number.isNaN(d.getTime())&&dayKey(d)===dayKey()}
function loadLocal(){try{return(JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')||[]).filter(x=>today(x.eaten_at))}catch{return[]}}
function saveLocal(){try{const old=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')||[],other=old.filter(x=>!today(x.eaten_at)),mine=entries.filter(x=>String(x.id||'').startsWith('local:'));localStorage.setItem(LOCAL_KEY,JSON.stringify([...other,...mine]))}catch{}}
async function rest(path,{method='GET',body,prefer}={}){const cfg=window.TrainingLab?.config,a=authState(),user=uid(a);if(!cfg?.url||!cfg?.key||!a?.access_token||!user)throw new Error('AUTH');const headers={apikey:cfg.key,Authorization:`Bearer ${a.access_token}`,Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json';if(prefer)headers.Prefer=prefer;const run=window.TrainingLab?.request||fetch,res=await run(`${cfg.url}/rest/v1/${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.status===204?null:res.json()}
async function refresh(){const a=authState(),user=uid(a);if(!user){entries=loadLocal();render();return}try{const rows=await rest(`meal_logs?select=id,eaten_at,meal_type,title,protein_g,carbs_g,fat_g&user_id=eq.${encodeURIComponent(user)}&order=eaten_at.desc&limit=200`);entries=(rows||[]).filter(x=>today(x.eaten_at));render()}catch{entries=(window.cloudMeals||[]).filter(x=>today(x.eaten_at));render()}}
function targets(){const el=document.getElementById('macroRemaining'),parsed=parseNutritionTargets(el?.textContent||'');if(parsed.carbs===DEFAULT_TARGETS.carbs){const m=(document.getElementById('carbPill')?.textContent||'').match(/(\d+)\s*g/i);if(m)parsed.carbs=Number(m[1])}return parsed}
function presetList(cat){return cat==='merienda'?NUTRITION_PRESETS.breakfast:NUTRITION_PRESETS[cat]||[]}
function mealType(cat){return cat==='breakfast'?breakfastMode:cat}
function mealName(type){return{desayuno:'Desayuno',recena:'Recena',comida:'Comida',merienda:'Merienda',cena:'Cena',picoteo:'Picoteo'}[type]||type||'Comida'}
function ring(label,total,target){const pct=target?Math.min(100,total/target*100):0,over=Math.max(0,total-target);return`<div class="nutrition-ring-card"><div class="nutrition-ring" style="--pct:${pct.toFixed(1)}"><div><strong>${round(total)}</strong><span>/ ${round(target)} g</span></div></div><b>${label}</b><small>${over?`+${round(over)} g sobre objetivo`:`Faltan ${round(Math.max(0,target-total))} g`}</small></div>`}
function foodButton(p,cat){return`<button class="nutrition-food-btn" type="button" data-preset-cat="${cat}" data-preset-id="${p.id}"><span>${esc(p.title)}</span><small>P ${p.protein} · HC ${p.carbs} · G ${p.fat} g · ${kcalFor(p)} kcal</small></button>`}
function otherForm(cat){if(openOther!==cat)return'';const d=draft?.category===cat?draft:null;return`<div class="nutrition-other-form" data-other="${cat}"><label>¿Qué has comido?</label><input data-desc placeholder="Ej. arroz con pollo y huevo / menú de restaurante" value="${esc(d?.description||'')}"><div class="nutrition-other-row"><label>Ración<select data-portion><option value="pequena"${d?.portion==='pequena'?' selected':''}>Pequeña</option><option value="normal"${!d||d.portion==='normal'?' selected':''}>Normal adulta</option><option value="grande"${d?.portion==='grande'?' selected':''}>Grande</option></select></label><button class="btn alt" type="button" data-estimate="${cat}">Estimar macros</button></div>${d?`<div class="nutrition-estimate"><p><strong>Estimación aproximada.</strong> Puedes corregirla antes de guardarla.${d.fallback?' No reconocí ingredientes concretos, así que he usado una ración media para este tipo de comida.':''}</p><div class="nutrition-macro-edit"><label>Proteína<input data-p type="number" min="0" value="${d.protein}"> g</label><label>HC<input data-c type="number" min="0" value="${d.carbs}"> g</label><label>Grasa<input data-f type="number" min="0" value="${d.fat}"> g</label></div><button class="btn" type="button" data-add-other="${cat}">Añadir a hoy</button></div>`:''}</div>`}
function section(cat){const mode=cat==='breakfast'?`<div class="nutrition-mode"><span>Registrar como</span><button type="button" data-mode="desayuno" class="${breakfastMode==='desayuno'?'on':''}">Desayuno</button><button type="button" data-mode="recena" class="${breakfastMode==='recena'?'on':''}">Recena</button></div>`:'';return`<section class="nutrition-meal-card"><div class="nutrition-meal-head"><div><span>¿Qué comiste?</span><h2>${LABELS[cat]}</h2></div><button class="btn alt" type="button" data-toggle-other="${cat}">+ Otros</button></div>${mode}<div class="nutrition-food-grid">${presetList(cat).map(p=>foodButton(p,cat)).join('')}</div>${otherForm(cat)}</section>`}
function logs(){if(!entries.length)return'<div class="nutrition-empty">Todavía no has registrado comida hoy.</div>';return [...entries].sort((a,b)=>Date.parse(b.eaten_at)-Date.parse(a.eaten_at)).map(x=>`<div class="nutrition-log-row"><div><span>${esc(mealName(x.meal_type))}</span><strong>${esc(x.title||'Comida')}</strong><small>P ${round(x.protein_g)} · HC ${round(x.carbs_g)} · G ${round(x.fat_g)} g</small></div><div><b>${kcalFor({protein:x.protein_g,carbs:x.carbs_g,fat:x.fat_g})} kcal</b><button type="button" data-delete="${esc(x.id)}" aria-label="Eliminar">×</button></div></div>`).join('')}
function render(){if(!root)return;const total=calculateNutritionTotals(entries),t=targets(),cloud=!!uid(authState());root.innerHTML=`<div class="nutrition-title"><div><span>Hoy</span><h1>¿Qué comiste hoy?</h1><p>Raciones adultas normales como referencia. Un toque suma el plato al día.</p></div><div class="nutrition-sync ${cloud?'is-cloud':'is-local'}">${cloud?'Sincronizado':'Modo local'}</div></div><section class="nutrition-progress"><div class="nutrition-rings">${ring('Proteína',total.protein,t.protein)}${ring('Carbohidratos',total.carbs,t.carbs)}${ring('Grasas',total.fat,t.fat)}</div><div class="nutrition-energy"><span>Total aproximado</span><strong>${kcalFor(total)} kcal</strong><small>Objetivo actual: P ${t.protein} · HC ${t.carbs} · G ${t.fat} g</small></div></section><div class="nutrition-categories">${['breakfast','comida','merienda','cena','picoteo'].map(section).join('')}</div><section class="nutrition-today-log"><div class="nutrition-log-head"><div><span>Registro</span><h2>Lo ingerido hoy</h2></div><b>${entries.length} ${entries.length===1?'registro':'registros'}</b></div>${logs()}</section><p class="nutrition-disclaimer">Los macros son estimaciones prácticas. En “Otros” puedes corregir P/HC/G antes de sumar el plato.</p>`}
async function add({type,title,protein,carbs,fat}){if(busy)return;busy=true;try{const a=authState(),user=uid(a),payload={meal_type:type,title,protein_g:round(protein),carbs_g:round(carbs),fat_g:round(fat),eaten_at:new Date().toISOString()};if(user){const rows=await rest('meal_logs?select=id,eaten_at,meal_type,title,protein_g,carbs_g,fat_g',{method:'POST',body:{user_id:user,...payload},prefer:'return=representation'}),row=rows?.[0];if(!row)throw new Error('SAVE');entries.unshift(row);window.cloudMeals=window.cloudMeals||[];window.cloudMeals.unshift(row)}else{entries.unshift({id:`local:${Date.now()}:${Math.random().toString(36).slice(2)}`,...payload});saveLocal()}draft=null;openOther=null;render();toast(`Añadido: ${title}`)}catch{toast('No se pudo guardar. Revisa la conexión.',true)}finally{busy=false}}
async function remove(id){if(busy)return;busy=true;try{if(String(id).startsWith('local:')){entries=entries.filter(x=>String(x.id)!==String(id));saveLocal()}else{const user=uid(authState());if(!user)throw new Error('AUTH');await rest(`meal_logs?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(user)}`,{method:'DELETE'});entries=entries.filter(x=>String(x.id)!==String(id));if(Array.isArray(window.cloudMeals))window.cloudMeals=window.cloudMeals.filter(x=>String(x.id)!==String(id))}render();toast('Registro eliminado')}catch{toast('No se pudo eliminar.',true)}finally{busy=false}}
function toast(msg,error=false){let e=document.querySelector('.nutrition-toast');if(!e){e=document.createElement('div');e.className='nutrition-toast';document.body.append(e)}e.textContent=msg;e.classList.toggle('is-error',error);e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function click(e){const p=e.target.closest('[data-preset-id]');if(p){const item=presetList(p.dataset.presetCat).find(x=>x.id===p.dataset.presetId);if(item)add({type:mealType(p.dataset.presetCat),title:item.title,protein:item.protein,carbs:item.carbs,fat:item.fat});return}const mode=e.target.closest('[data-mode]');if(mode){breakfastMode=mode.dataset.mode;render();return}const tog=e.target.closest('[data-toggle-other]');if(tog){openOther=openOther===tog.dataset.toggleOther?null:tog.dataset.toggleOther;draft=null;render();return}const est=e.target.closest('[data-estimate]');if(est){const cat=est.dataset.estimate,form=root.querySelector(`[data-other="${cat}"]`),description=form?.querySelector('[data-desc]')?.value.trim()||'',portion=form?.querySelector('[data-portion]')?.value||'normal';if(!description){toast('Escribe el plato para estimarlo.',true);return}draft={category:cat,description,...estimateOtherMeal(description,cat,portion)};render();return}const other=e.target.closest('[data-add-other]');if(other&&draft){const cat=other.dataset.addOther,form=root.querySelector(`[data-other="${cat}"]`);add({type:mealType(cat),title:draft.description,protein:form.querySelector('[data-p]').value,carbs:form.querySelector('[data-c]').value,fat:form.querySelector('[data-f]').value});return}const del=e.target.closest('[data-delete]');if(del)remove(del.dataset.delete)}
function install(){const page=document.getElementById('comer');if(!page||page.querySelector('.nutrition-tracker-root'))return;ensureCss();const h=new Date().getHours();breakfastMode=h>=1&&h<8?'recena':'desayuno';root=document.createElement('div');root.className='nutrition-tracker-root';page.prepend(root);root.addEventListener('click',click);render();setTimeout(refresh,150);setTimeout(refresh,1700);const legacy=document.getElementById('macroRemaining');if(legacy)new MutationObserver(render).observe(legacy,{subtree:true,childList:true,characterData:true});document.addEventListener('click',e=>{if(e.target.closest('button[data-page="comer"]'))setTimeout(refresh,80)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()})}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else queueMicrotask(install)}
