const SUPABASE_URL='https://nnpvklaxhomarxszlclt.supabase.co';
const SUPABASE_KEY='sb_publishable_4zzi_K9QK12-qtD4RG2Gxg_TyXX1TBd';
const AUTH_KEY='sb-nnpvklaxhomarxszlclt-auth-token';
const CSS_URL='./personal-records.css?v=20260911records93';
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const canonical=t=>({running:'run',bike:'cycling',biking:'cycling',cycle:'cycling',strength:'gym'}[String(t||'').toLowerCase()]||String(t||'').toLowerCase());
const RULES={
 football:[
  {key:'robustTopKmh',label:'Velocidad robusta',unit:'km/h',mode:'max',minDelta:0.3,valid:s=>finite(s.robustTopKmh)},
  {key:'metersPerMovingMin',label:'Metros por minuto',unit:'m/min',mode:'max',minDelta:1.5,valid:s=>finite(s.metersPerMovingMin)},
  {key:'sprintDensityPer10Min',label:'Densidad de sprint',unit:'/10 min',mode:'max',minDelta:0.2,valid:s=>finite(s.sprintDensityPer10Min)},
  {key:'fatigueRetention',label:'Retención final',unit:'ratio',mode:'max',minDelta:.015,valid:s=>finite(s.fatigueRetention)&&Number(s.fatigueRetention)>=.5&&Number(s.fatigueRetention)<=1.3}
 ],
 run:[
  {key:'avgPaceSecKm',label:'Mejor ritmo medio',unit:'pace',mode:'min',minDelta:3,valid:s=>finite(s.avgPaceSecKm)&&finite(s.distanceKm)&&Number(s.distanceKm)>=3},
  {key:'fastestKmPaceSec',label:'Kilómetro más rápido',unit:'pace',mode:'min',minDelta:2,valid:s=>finite(s.fastestKmPaceSec)},
  {key:'paceRegularityPct',label:'Mejor regularidad',unit:'pct',mode:'min',minDelta:.25,valid:s=>finite(s.paceRegularityPct)&&Number(s.paceRegularityPct)>=0}
 ],
 cycling:[
  {key:'avgSpeedKmh',label:'Velocidad media',unit:'km/h',mode:'max',minDelta:.3,valid:s=>finite(s.avgSpeedKmh)&&finite(s.distanceKm)&&Number(s.distanceKm)>=10},
  {key:'avgPowerW',label:'Potencia media',unit:'W',mode:'max',minDelta:5,valid:s=>finite(s.avgPowerW)&&finite(s.durationSec)&&Number(s.durationSec)>=1200},
  {key:'robustCyclingSpeedKmh',label:'Pico robusto',unit:'km/h',mode:'max',minDelta:.5,valid:s=>finite(s.robustCyclingSpeedKmh)}
 ]
};
function authState(){try{const d=localStorage.getItem(AUTH_KEY);if(d){const p=JSON.parse(d);if(p?.access_token)return p}for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('sb-')||!k.endsWith('-auth-token'))continue;const p=JSON.parse(localStorage.getItem(k)||'null');if(p?.access_token&&k.includes('nnpvklaxhomarxszlclt'))return p}}catch{}return null}
async function rest(table,params,token){const url=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const [k,v] of Object.entries(params||{}))if(v!==null&&v!==undefined)url.searchParams.set(k,String(v));const r=await fetch(url,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function valueText(v,unit){if(!finite(v))return'—';const n=Number(v);if(unit==='pace'){const s=Math.round(n);return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}/km`}if(unit==='ratio')return`${(n*100).toFixed(0)}%`;if(unit==='pct')return`${n.toFixed(1)}%`;if(unit==='km/h')return`${n.toFixed(1)} km/h`;if(unit==='m/min')return`${n.toFixed(1)} m/min`;if(unit==='/10 min')return`${n.toFixed(1)} /10 min`;if(unit==='W')return`${Math.round(n)} W`;if(unit==='kg')return`${n.toFixed(1)} kg`;return String(n)}
function better(a,b,mode){return mode==='min'?a<b:a>b}
export function calculateRecords(type,sessions=[]){const sport=canonical(type),rules=RULES[sport]||[],ordered=(Array.isArray(sessions)?sessions:[]).filter(x=>x&&x.date).sort((a,b)=>new Date(a.date)-new Date(b.date)),latest=ordered.at(-1),out=[];if(ordered.length<2)return out;for(const rule of rules){const valid=ordered.filter(rule.valid);if(valid.length<2)continue;let best=valid[0];for(const s of valid.slice(1))if(better(Number(s[rule.key]),Number(best[rule.key]),rule.mode))best=s;const prior=valid.filter(x=>x!==best&&new Date(x.date)<new Date(best.date));let priorBest=null;if(prior.length){priorBest=prior[0];for(const s of prior.slice(1))if(better(Number(s[rule.key]),Number(priorBest[rule.key]),rule.mode))priorBest=s}const improvement=priorBest?Math.abs(Number(best[rule.key])-Number(priorBest[rule.key])):null,newRecord=best===latest&&priorBest&&improvement>=rule.minDelta;out.push({...rule,value:Number(best[rule.key]),date:best.date,activityId:best.id,newRecord:!!newRecord,improvement,previous:priorBest?Number(priorBest[rule.key]):null})}return out}
export function calculateStrengthRecords(reports=[]){const byExercise=new Map();for(const item of reports||[]){const details=item?.report?.details?.exercises;if(!Array.isArray(details))continue;for(const ex of details){if(!finite(ex?.bestE1rmKg)||!ex?.exercise)continue;const name=String(ex.exercise).trim(),key=name.toLowerCase(),row={exercise:name,value:Number(ex.bestE1rmKg),date:item.date,id:item.id};const list=byExercise.get(key)||[];list.push(row);byExercise.set(key,list)}}const records=[];for(const list of byExercise.values()){list.sort((a,b)=>new Date(a.date)-new Date(b.date));if(list.length<2)continue;let best=list[0];for(const x of list.slice(1))if(x.value>best.value)best=x;const latest=list.at(-1),prior=list.filter(x=>new Date(x.date)<new Date(best.date));let priorBest=prior.length?prior.reduce((a,b)=>a.value>=b.value?a:b):null;const improvement=priorBest?best.value-priorBest.value:null;records.push({label:best.exercise,unit:'kg',value:best.value,date:best.date,activityId:best.id,newRecord:best===latest&&priorBest&&improvement>=.5,improvement,previous:priorBest?.value??null})}return records.sort((a,b)=>b.value-a.value).slice(0,6)}
function ensureCss(){if(document.querySelector('link[data-personal-records-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS_URL;l.dataset.personalRecordsCss='1';document.head.append(l)}
function renderGroup(title,icon,records){if(!records.length)return'';return`<div class="record-group"><div class="record-group-title"><strong>${esc(icon)} ${esc(title)}</strong><span>${records.length} marcas</span></div><div class="record-grid">${records.map(r=>`<div class="record-card ${r.newRecord?'is-new':''}">${r.newRecord?'<b>NUEVO RÉCORD</b>':''}<span>${esc(r.label)}</span><strong>${esc(valueText(r.value,r.unit))}</strong><small>${new Date(r.date).toLocaleDateString('es-ES',{day:'2-digit',month:'short',year:'2-digit'})}${r.previous!==null&&r.previous!==undefined?` · anterior ${esc(valueText(r.previous,r.unit))}`:''}</small></div>`).join('')}</div></div>`}
let loaded=false;
async function load(force=false){const page=document.getElementById('progreso');if(!page)return;ensureCss();let shell=page.querySelector('.personal-records-shell');if(!shell){shell=document.createElement('section');shell.className='card personal-records-shell';const progress=page.querySelector('.sports-progress-shell');if(progress)progress.insertAdjacentElement('afterend',shell);else page.querySelector('#weeklyReportCard')?.insertAdjacentElement('afterend',shell)}if(loaded&&!force)return;const auth=authState();if(!auth?.access_token){shell.innerHTML='<div class="activity-analysis-kicker">Récords personales</div><p class="muted">Inicia sesión para calcular tus mejores marcas.</p>';return}shell.innerHTML='<div class="activity-analysis-kicker">Récords personales</div><p class="muted">Calculando mejores marcas…</p>';try{const activities=await rest('activities',{select:'id,activity_type,activity_date,started_at,distance_km',order:'started_at.asc.nullslast,activity_date.asc',limit:200},auth.access_token),ids=(activities||[]).map(x=>x.id).filter(Boolean),analyses=ids.length?await rest('activity_analysis',{select:'activity_id,summary,report',activity_id:`in.(${ids.join(',')})`},auth.access_token):[],map=new Map((analyses||[]).map(x=>[String(x.activity_id),x])),groups={football:[],run:[],cycling:[],gym:[]};for(const a of activities||[]){const type=canonical(a.activity_type);if(!groups[type])continue;const an=map.get(String(a.id))||{},summary={...(an.summary||{})};if(!finite(summary.distanceKm)&&finite(a.distance_km))summary.distanceKm=Number(a.distance_km);groups[type].push({...summary,id:a.id,date:a.started_at||a.activity_date,report:an.report})}const football=calculateRecords('football',groups.football),run=calculateRecords('run',groups.run),cycling=calculateRecords('cycling',groups.cycling),gym=calculateStrengthRecords(groups.gym);shell.innerHTML=`<div class="records-head"><div><div class="activity-analysis-kicker">Récords personales</div><h2>Mejores marcas fiables</h2></div><span class="muted small">sin premiar ruido mínimo</span></div>${renderGroup('Fútbol','⚽',football)}${renderGroup('Running','🏃',run)}${renderGroup('Ciclismo','🚴',cycling)}${renderGroup('Fuerza · 1RM estimado','🏋️',gym)}${![football,run,cycling,gym].some(x=>x.length)?'<p class="muted">Aún hacen falta más sesiones comparables para establecer récords.</p>':''}<p class="activity-analysis-note">Los récords de 1RM son estimaciones Epley. Potencia, velocidad y ritmo solo se consideran cuando hay datos suficientes y filtros mínimos de duración/distancia.</p>`;loaded=true}catch(error){shell.innerHTML=`<div class="activity-analysis-kicker">Récords personales</div><p class="muted">No se pudieron calcular los récords: ${esc(error?.message||error)}</p>`}}
function install(){document.addEventListener('click',event=>{if(event.target.closest?.('[data-page="progreso"]'))setTimeout(()=>load(false),45)});if(document.getElementById('progreso')?.classList.contains('on'))load(false)}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,0)}
export {valueText};
