import {authState,dayKey,esc,rest} from './training-data.js?v=20260911overhaul110';
const CSS='./sleep-weekly.css?v=20260911overhaul110';
let loaded=false;
function css(){if(document.querySelector('link[data-sleep-weekly]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.sleepWeekly='1';document.head.append(l)}
function fmt(min){const n=Math.max(0,Math.round(Number(min)||0));return`${Math.floor(n/60)} h ${String(n%60).padStart(2,'0')}`}
function date(v){const d=new Date(`${v}T12:00:00`);return d.toLocaleDateString('es-ES',{weekday:'short',day:'numeric'}).replace('.','')}
function rangeDays(){const out=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);out.push(dayKey(d))}return out}
function pct(v,total){return total>0?Math.max(0,Number(v)||0)/total*100:0}
function score(r){if(Number.isFinite(Number(r.sleep_score))&&Number(r.sleep_score)>0)return Math.round(Number(r.sleep_score));const total=Number(r.total_sleep_min)||0,duration=Math.min(100,total/480*100),deep=pct(r.deep_sleep_min,total),rem=pct(r.rem_sleep_min,total),stages=Math.min(100,70+Math.min(15,deep)*.7+Math.min(25,rem)*.45);return Math.round(duration*.72+stages*.28)}
function bar(r,max){if(!r)return`<div class="sleep-week-col is-empty"><div class="sleep-week-bar"><i></i></div></div>`;const total=Math.max(1,Number(r.total_sleep_min)||0),height=Math.max(11,total/max*100),deep=pct(r.deep_sleep_min,total),rem=pct(r.rem_sleep_min,total),light=Math.max(0,100-deep-rem-pct(r.awake_min,total));return`<div class="sleep-week-col"><div class="sleep-week-value">${fmt(total)}</div><div class="sleep-week-bar" style="--sleep-height:${height}%" title="${esc(fmt(total))}"><div class="sleep-week-stack"><span class="sleep-deep" style="height:${deep}%"></span><span class="sleep-rem" style="height:${rem}%"></span><span class="sleep-light" style="height:${light}%"></span></div></div></div>`}
function verdict(rows){if(!rows.length)return'Necesitamos varias noches sincronizadas para comparar la semana.';const totals=rows.map(x=>Number(x.total_sleep_min)||0).filter(Boolean),avg=totals.reduce((a,b)=>a+b,0)/totals.length,min=Math.min(...totals),max=Math.max(...totals),spread=max-min;if(rows.length<3)return`Hay ${rows.length} noches disponibles. La media provisional es ${fmt(avg)}.`;if(avg>=450&&spread<90)return`Semana bastante estable: media ${fmt(avg)} y poca variación entre noches.`;if(avg<420)return`La media semanal está en ${fmt(avg)}. Antes de añadir carga, interesa recuperar tiempo de sueño de forma sostenida.`;if(spread>=150)return`Duración irregular: hay ${fmt(spread)} entre la noche más corta y la más larga. La regularidad puede ser un objetivo más útil que perseguir una fase concreta.`;return`Media semanal ${fmt(avg)}. Mira la tendencia de varias noches y úsala junto con fatiga y carga de entrenamiento.`}
async function render(force=false){const page=document.getElementById('sueno');if(!page||!authState()?.access_token)return;css();let root=page.querySelector('.sleep-weekly-root');if(!root){root=document.createElement('section');root.className='card sleep-weekly-root';const last=page.querySelector('.sleep-overview');last?.insertAdjacentElement('beforebegin',root)}if(loaded&&!force)return;root.innerHTML='<span class="muted">Cargando semana de sueño…</span>';try{const days=rangeDays(),rows=await rest('sleep_records',{select:'sleep_date,total_sleep_min,deep_sleep_min,rem_sleep_min,light_sleep_min,awake_min,sleep_score,sleep_start,sleep_end,avg_hrv,resting_hr',sleep_date:`gte.${days[0]}`,order:'sleep_date.asc',limit:14}),by=new Map((rows||[]).map(r=>[r.sleep_date,r])),available=days.map(d=>by.get(d)).filter(Boolean),max=Math.max(480,...available.map(x=>Number(x.total_sleep_min)||0)),avgScore=available.length?Math.round(available.reduce((s,x)=>s+score(x),0)/available.length):null;root.innerHTML=`<div class="sleep-week-head"><div><span class="eyebrow">Últimas 7 noches</span><h2>Comparación semanal</h2><p>${esc(verdict(available))}</p></div><div class="sleep-week-score"><span>Media</span><b>${avgScore??'—'}</b><small>puntuación orientativa</small></div></div><div class="sleep-week-chart">${days.map(d=>`<div class="sleep-week-day">${bar(by.get(d),max)}<b>${esc(date(d))}</b></div>`).join('')}</div><div class="sleep-week-legend"><span><i class="sleep-deep"></i>Profundo</span><span><i class="sleep-rem"></i>REM</span><span><i class="sleep-light"></i>Ligero/otros</span></div><p class="sleep-week-note">La altura compara duración total; los colores muestran la composición de cada noche. No conviene interpretar diferencias pequeñas de fases como cambios clínicos.</p>`;loaded=true}catch(e){root.innerHTML=`<p class="muted">No se pudo cargar la semana de sueño: ${esc(e?.message||e)}</p>`}}
function simplifyLastNight(){const page=document.getElementById('sueno'),overview=page?.querySelector('.sleep-overview');if(!overview)return;overview.classList.add('sleep-coros-style');const bar=overview.querySelector('#sleepStageBar');if(bar)bar.setAttribute('aria-label','Composición de la última noche por fases')}
function install(){css();simplifyLastNight();document.addEventListener('click',e=>{if(e.target.closest?.('[data-page="sueno"]'))setTimeout(()=>{simplifyLastNight();render(true)},60)});setTimeout(()=>render(false),800)}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,0)}
