const AUTH_KEY='sb-nnpvklaxhomarxszlclt-auth-token';
const CSS_URL='./trend-coach.css?v=20260911coach95';
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const median=values=>{const a=values.filter(finite).map(Number).sort((a,b)=>a-b);if(!a.length)return null;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const canonical=t=>({running:'run',bike:'cycling',biking:'cycling',cycle:'cycling',strength:'gym'}[String(t||'').toLowerCase()]||String(t||'').toLowerCase());
function authState(){try{const d=localStorage.getItem(AUTH_KEY);if(d){const p=JSON.parse(d);if(p?.access_token)return p}for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('sb-')||!k.endsWith('-auth-token'))continue;const p=JSON.parse(localStorage.getItem(k)||'null');if(p?.access_token&&k.includes('nnpvklaxhomarxszlclt'))return p}}catch{}return null}
async function rest(table,params,token){const cfg=window.TrainingLab?.config;if(!cfg?.url||!cfg?.key)throw new Error('Configuración cloud no disponible');const url=new URL(`${cfg.url}/rest/v1/${table}`);for(const [k,v] of Object.entries(params||{}))if(v!==null&&v!==undefined)url.searchParams.set(k,String(v));const r=await window.TrainingLab.request(url.href,{headers:{apikey:cfg.key,Authorization:`Bearer ${token}`,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function pct(latest,base){return finite(latest)&&finite(base)&&Number(base)!==0?(Number(latest)-Number(base))/Math.abs(Number(base))*100:null}
function priorMedian(rows,key){return median(rows.slice(0,-1).slice(-5).map(x=>x?.[key]))}
function sportSignals(type,rows){if(!Array.isArray(rows)||rows.length<3)return[];const latest=rows.at(-1),signals=[];
 if(type==='football'){
  const retentionBase=priorMedian(rows,'fatigueRetention'),recoveryBase=priorMedian(rows,'avgSprintRecoveryS'),workBase=priorMedian(rows,'metersPerMovingMin'),retentionDelta=pct(latest.fatigueRetention,retentionBase),recoveryDelta=pct(latest.avgSprintRecoveryS,recoveryBase),workDelta=pct(latest.metersPerMovingMin,workBase);
  if(finite(retentionDelta)&&retentionDelta<=-5&&finite(recoveryDelta)&&recoveryDelta>=10)signals.push({tone:'attention',sport:'Fútbol',title:'Asimilar mejor la carga del partido',text:'La retención final ha bajado y la recuperación entre sprints se alargó frente a tu referencia. Evita añadir intensidad extra solo por completar volumen y prioriza recuperación entre partidos.'});
  else if(finite(workDelta)&&workDelta>=5&&(!finite(retentionDelta)||retentionDelta>=-3))signals.push({tone:'positive',sport:'Fútbol',title:'Trabajo de partido bien sostenido',text:'Suben los metros por minuto sin una caída clara de retención final. Mantén la estructura actual antes de aumentar carga.'});
 }
 if(type==='run'){
  const paceBase=priorMedian(rows,'avgPaceSecKm'),hrBase=priorMedian(rows,'avgHr'),paceDelta=pct(latest.avgPaceSecKm,paceBase),hrDelta=finite(latest.avgHr)&&finite(hrBase)?Number(latest.avgHr)-Number(hrBase):null;
  if(finite(paceDelta)&&paceDelta<=-3&&(!finite(hrDelta)||Math.abs(hrDelta)<=4))signals.push({tone:'positive',sport:'Running',title:'La base aeróbica progresa',text:'El ritmo mejora con un coste cardíaco parecido. Mantén los rodajes fáciles; no hace falta convertirlos en sesiones más duras.'});
  else if(finite(hrDelta)&&hrDelta>=7&&(!finite(paceDelta)||paceDelta>=-2))signals.push({tone:'attention',sport:'Running',title:'Próximo rodaje: realmente fácil',text:'La FC media subió sin una mejora clara de ritmo. Mantén el próximo rodaje conversacional y revisa contexto como sueño, calor y fatiga.'});
 }
 if(type==='cycling'){
  const speedBase=priorMedian(rows,'avgSpeedKmh'),hrBase=priorMedian(rows,'avgHr'),driftBase=priorMedian(rows,'cardiacDriftPct'),speedDelta=pct(latest.avgSpeedKmh,speedBase),hrDelta=finite(latest.avgHr)&&finite(hrBase)?Number(latest.avgHr)-Number(hrBase):null,driftDelta=pct(latest.cardiacDriftPct,driftBase);
  if(finite(speedDelta)&&speedDelta>=4&&(!finite(hrDelta)||Math.abs(hrDelta)<=4))signals.push({tone:'positive',sport:'Ciclismo',title:'Mejor eficiencia en bici',text:'La velocidad media mejora con un pulso parecido. Conserva la carga antes de perseguir más vatios.'});
  else if(finite(driftDelta)&&driftDelta>=25&&finite(latest.cardiacDriftPct)&&Number(latest.cardiacDriftPct)>=6)signals.push({tone:'attention',sport:'Ciclismo',title:'Controla la deriva en salidas largas',text:'La deriva cardíaca reciente está por encima de tu referencia. Interprétala junto a desnivel, calor, hidratación y objetivo de la salida.'});
 }
 if(type==='gym'){
  const currentExercise=String(latest.bestEstimated1RmExercise||'').toLowerCase(),same=rows.slice(0,-1).slice(-5).filter(x=>String(x.bestEstimated1RmExercise||'').toLowerCase()===currentExercise&&finite(x.bestEstimated1RmKg)),base=median(same.map(x=>x.bestEstimated1RmKg)),strengthDelta=pct(latest.bestEstimated1RmKg,base);
  if(currentExercise&&same.length>=2&&finite(strengthDelta)&&strengthDelta>=2)signals.push({tone:'positive',sport:'Fuerza',title:'Progresión de fuerza compatible',text:`El 1RM estimado de ${latest.bestEstimated1RmExercise} mejora frente a sesiones comparables. Mantén técnica y progresión gradual; es una estimación, no una prueba máxima.`});
 }
 return signals;
}
export function buildTrendCoach(groups={}){const all=[];for(const type of ['football','run','cycling','gym'])all.push(...sportSignals(type,groups[type]||[]));const attention=all.filter(x=>x.tone==='attention'),positive=all.filter(x=>x.tone==='positive'),selected=[...attention,...positive].slice(0,3);let focus='Acumular sesiones comparables antes de cambiar el plan por tendencias.';if(attention.length)focus='Prioridad: asimilar carga y mantener calidad. Readiness, sueño y molestias siguen mandando sobre el histórico.';else if(positive.length)focus='La tendencia acompaña. Mantén la estructura actual antes de subir volumen o intensidad.';return{signals:selected,focus,totalSignals:all.length}}
function ensureCss(){if(document.querySelector('link[data-trend-coach-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS_URL;l.dataset.trendCoachCss='1';document.head.append(l)}
function render(model){return`<div class="trend-coach-head"><div><div class="eyebrow">Histórico → plan</div><h2>Lo que dice tu evolución</h2></div><span class="muted small">señal secundaria</span></div><p class="trend-coach-focus">${esc(model.focus)}</p>${model.signals.length?`<div class="trend-coach-list">${model.signals.map(s=>`<article class="trend-coach-signal is-${s.tone}"><span>${esc(s.sport)}</span><strong>${esc(s.title)}</strong><p>${esc(s.text)}</p></article>`).join('')}</div>`:'<p class="muted">Todavía no hay una tendencia deportiva suficientemente estable para condicionar recomendaciones.</p>'}<p class="activity-analysis-note">Estas señales no sustituyen dolor, señales de alarma, sueño, readiness ni el contexto real del entrenamiento.</p>`}
let loaded=false;
async function load(force=false){const page=document.getElementById('semana');if(!page)return;ensureCss();let shell=page.querySelector('.trend-coach-shell');if(!shell){shell=document.createElement('section');shell.className='card section trend-coach-shell';const coach=page.querySelector('#coachTasks')?.closest('.card');coach?.insertAdjacentElement('afterend',shell)}if(!shell||loaded&&!force)return;const auth=authState();if(!auth?.access_token){shell.innerHTML='<div class="eyebrow">Histórico → plan</div><p class="muted">Inicia sesión para usar tendencias sincronizadas.</p>';return}shell.innerHTML='<div class="eyebrow">Histórico → plan</div><p class="muted">Leyendo evolución reciente…</p>';try{const activities=await rest('activities',{select:'id,activity_type,activity_date,started_at,avg_hr',order:'started_at.asc.nullslast,activity_date.asc',limit:120},auth.access_token),ids=(activities||[]).map(x=>x.id).filter(Boolean),analyses=ids.length?await rest('activity_analysis',{select:'activity_id,summary',activity_id:`in.(${ids.join(',')})`},auth.access_token):[],map=new Map((analyses||[]).map(x=>[String(x.activity_id),x.summary||{}])),groups={football:[],run:[],cycling:[],gym:[]};for(const a of activities||[]){const type=canonical(a.activity_type);if(!groups[type])continue;const s={...(map.get(String(a.id))||{}),date:a.started_at||a.activity_date};if(!finite(s.avgHr)&&finite(a.avg_hr))s.avgHr=Number(a.avg_hr);groups[type].push(s)}shell.innerHTML=render(buildTrendCoach(groups));loaded=true}catch(error){shell.innerHTML=`<div class="eyebrow">Histórico → plan</div><p class="muted">No se pudo leer la tendencia: ${esc(error?.message||error)}</p>`}}
function install(){document.addEventListener('click',e=>{if(e.target.closest?.('[data-page="semana"]'))setTimeout(()=>load(false),25)});if(document.getElementById('semana')?.classList.contains('on'))load(false)}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else setTimeout(install,0)}
