import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {analyzeCyclingSession} from '../supabase/functions/analyze-fit/analysis/cycling.js';
import {buildBaseFitAnalysis} from '../supabase/functions/analyze-fit/analysis/base-analysis.js';
import {makeReport} from '../supabase/functions/analyze-fit/analysis/generic-report.js';
import {num,textValue,ts} from '../supabase/functions/analyze-fit/analysis/edge-common.js';
import {makeStrengthReport,normalizeStrengthSets} from '../supabase/functions/analyze-fit/analysis/strength.js';
import {persistFitAnalysis} from '../supabase/functions/analyze-fit/analysis/persist-analysis.js';
function parsedRide(){const start=new Date('2026-09-11T08:00:00Z').getTime(),records=[];let distance=0;for(let i=0;i<=2400;i++){const speed=28,dKm=speed/3600;distance+=dKm;records.push({timestamp:new Date(start+i*1000),distance,enhanced_speed:speed,heart_rate:132+Math.round(i/2400*12),enhanced_altitude:.08+Math.sin(i/160)*.002,cadence:88,power:205,position_lat:Math.round((39.47+i*1e-7)/180*2147483648),position_long:Math.round((-0.38+i*1e-7)/180*2147483648)});}return{records,sessions:[{sport:'cycling',total_elapsed_time:2400,total_timer_time:2400,total_distance:distance,avg_heart_rate:138,max_heart_rate:145,total_calories:520,avg_power:205,max_power:450,threshold_power:240}]}}
class FakeFitParser{constructor(){}async parseAsync(){return parsedRide()}}
function fitBlob(){const b=new Uint8Array(14);b.set(new TextEncoder().encode('.FIT'),8);return new Blob([b])}
function edge(){let handler;const writes=[];const client={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},storage:{from:()=>({download:async()=>({data:fitBlob()})})},from:table=>{const q={select(){return q;},eq(){return q;},single:async()=>({data:table==='fit_files'?{id:'fit',user_id:'owner',activity_id:'activity',storage_path:'owner/ride.fit',original_name:'ride.fit'}:{id:'activity',activity_type:'cycling'}}),maybeSingle:async()=>({data:{hr_max_bpm:190}}),update(row){writes.push({table,row});return q;},delete(){return q;},insert(row){writes.push({table,row});return q;},upsert(row){writes.push({table,row});return q;},then(resolve){return Promise.resolve({error:null}).then(resolve)}};return q;}};const source=readFileSync('supabase/functions/analyze-fit/index.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace('export default handler;','');const context={Response,Request,Blob,TextDecoder,TextEncoder,createClient:()=>client,FitParser:FakeFitParser,analyzeFootballSession:()=>null,analyzeRunningSession:()=>null,analyzeCyclingSession,buildBaseFitAnalysis,makeReport,num,textValue,ts,makeStrengthReport,normalizeStrengthSets,persistFitAnalysis,Deno:{env:{get:()=>''},serve:fn=>handler=fn}};vm.runInNewContext(stripTypeScriptTypes(source),context);return{handler,writes}}

test('cycling FIT uses deep cycling analyzer, power zones and cycling analysis version',async()=>{const {handler,writes}=edge(),req=new Request('http://local',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify({fit_file_id:'fit'})}),response=await handler(req),body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.equal(body.summary.cyclingAnalysisVersion,'cycling-v1');assert.equal(body.report.sport,'cycling');assert.equal(body.summary.cyclingFtpW,240);assert.equal(body.summary.powerZonesAvailable,true);const analysis=writes.find(x=>x.table==='activity_analysis'&&x.row?.analysis_version);assert.equal(analysis?.row?.analysis_version,'fit-v6-cycling-v1');const activity=writes.find(x=>x.table==='activities'&&x.row?.metrics?.cyclingAnalysisVersion);assert.ok(activity);assert.equal(activity.row.avg_pace_sec_km,null);assert.ok(activity.row.metrics.avgSpeedKmh>20);});
