import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeFootballSession,normalizeFootballSamples,detectRelativeSprintPeaks,buildFatigueProfile} from '../supabase/functions/analyze-fit/analysis/football.js';
function makePoints({duration=1800,pattern='steady',gps=true}={}){const start=Date.UTC(2026,8,10,20,0,0);let distKm=0,lat=39.47,lon=-0.38;const pts=[];for(let t=0;t<=duration;t++){let speed=7;const cycle=t%120;if(cycle>=20&&cycle<28)speed=20+3*Math.sin((cycle-20)/8*Math.PI);if(pattern==='fade'&&t>duration*.65){speed*=.78;if(cycle>=20&&cycle<28)speed=Math.min(speed,16.5)}if(pattern==='hardfinish'&&t>duration*.65)speed*=1.08;const d=speed/3.6;distKm+=d/1000;if(gps){lat+=d/111320*.65;lon+=d/(111320*Math.cos(lat*Math.PI/180))*.35}pts.push({t:start+t*1000,speed,distanceKm:distKm,hr:Math.round(120+speed*2.2),lat:gps?lat:null,lon:gps?lon:null})}return pts}
test('normalizes FIT-like points and distance increments',()=>{const samples=normalizeFootballSamples(makePoints({duration:30}));assert.equal(samples[0].tSec,0);assert.ok(samples.at(-1).tSec>=30);assert.ok(samples.slice(1).some(x=>x.dIncM>0))});
test('relative sprint model returns enriched events',()=>{const samples=normalizeFootballSamples(makePoints({duration:1200})),result=detectRelativeSprintPeaks(samples,1200);assert.equal(result.model,'relative_peak_v3');assert.ok(result.eventSummary.count>=5);assert.ok(result.sprints.every(x=>Number.isFinite(x.startSec)&&Number.isFinite(x.endSec)));assert.ok(result.sprints.some(x=>x.distanceM>0));assert.ok(result.eventSummary.densityPer10Min>0)});
test('deep football analysis separates relative and absolute efforts',()=>{const result=analyzeFootballSession(makePoints({duration:1800}),{durationSec:1800,movingTimeSec:1800,distanceKm:5,avgHr:145,maxHr:181,highIntensityM:800,highIntensityShare:.16,metersPerMovingMin:166.7,hrZone45Share:.45,accelerations:20,decelerations:18,rawTopKmh:23,p99TopKmh:22,robustTopKmh:22.5});assert.equal(result.summaryPatch.footballAnalysisVersion,'football-v1');assert.ok(result.summaryPatch.relativeSprintEventCount>0);assert.ok(result.summaryPatch.absoluteSprintCount>0);assert.ok(result.summaryPatch.relativeSprintDistanceM>0);assert.ok(result.report.sections.sprints.detalle_eventos.length>0)});
test('report contains structured deep sections',()=>{const result=analyzeFootballSession(makePoints({duration:1800}),{durationSec:1800,movingTimeSec:1700,distanceKm:4.8,avgHr:149,maxHr:183,highIntensityM:760,highIntensityShare:.158,metersPerMovingMin:169,hrZone45Share:.5,accelerations:25,decelerations:20,rawTopKmh:23,p99TopKmh:22,robustTopKmh:22.5});for(const key of ['carga','velocidad','sprints','intensidad','fatiga','espacial'])assert.ok(result.report.sections[key],key);assert.equal(result.report.version,'football-report-v1');assert.equal(result.report.sport,'football')});
test('busiest 10 minute window is produced for long matches',()=>{const result=analyzeFootballSession(makePoints({duration:1800}),{durationSec:1800,movingTimeSec:1800,distanceKm:5,highIntensityM:700,highIntensityShare:.14,metersPerMovingMin:166});assert.ok(result.summaryPatch.busiest10MinM>0);assert.ok(Number.isFinite(result.summaryPatch.busiest10MinStartSec))});
test('fatigue profile is conservative and reports evidence',()=>{const samples=normalizeFootballSamples(makePoints({duration:2400,pattern:'fade'})),sprints=detectRelativeSprintPeaks(samples,2400).sprints,fatigue=buildFatigueProfile(samples,sprints,2400);assert.equal(fatigue.available,true);assert.ok(['clear','mild','stable','unknown'].includes(fatigue.summary.level));assert.ok(fatigue.summary.evidence.capacitySignals>=1);assert.ok(Array.isArray(fatigue.summary.notes))});
test('short activity does not claim fatigue',()=>{const result=analyzeFootballSession(makePoints({duration:600}),{durationSec:600,movingTimeSec:590,distanceKm:1.5,highIntensityM:150,highIntensityShare:.1,metersPerMovingMin:152});assert.equal(result.report.sections.fatiga.lectura,'Duración insuficiente');assert.equal(result.summaryPatch.fatigueLevel,null)});
test('spatial analysis stays relative and does not infer tactics',()=>{const result=analyzeFootballSession(makePoints({duration:1200,gps:true}),{durationSec:1200,movingTimeSec:1180,distanceKm:3,highIntensityM:400,highIntensityShare:.13,metersPerMovingMin:152}),spatial=result.report.sections.espacial;assert.equal(spatial.disponible,true);assert.equal(spatial.orientacion_tactica,'no inferida');assert.ok(spatial.grid.length>0)});
test('missing GPS keeps deep analysis usable without spatial claims',()=>{const result=analyzeFootballSession(makePoints({duration:1200,gps:false}),{durationSec:1200,movingTimeSec:1180,distanceKm:3,highIntensityM:400,highIntensityShare:.13,metersPerMovingMin:152});assert.equal(result.report.sections.espacial.disponible,false);assert.match(result.report.observations.at(-1),/No hay GPS suficiente/)});
test('empty points fail gracefully',()=>{const result=analyzeFootballSession([],{durationSec:3600,distanceKm:5});assert.equal(result.summaryPatch.footballAnalysisVersion,'football-v1');assert.equal(result.report,null);assert.equal(result.details,null)});
