import { createClient } from "@supabase/supabase-js";
import FitParser from "fit-file-parser";
import { analyzeFootballSession } from "./analysis/football.js";
import { analyzeFutsalSession } from "./analysis/futsal.js";
import { analyzeRunningSession } from "./analysis/running.js";
import { analyzeCyclingSession } from "./analysis/cycling.js";
import { buildBaseFitAnalysis } from "./analysis/base-analysis.js";
import { makeReport } from "./analysis/generic-report.js";
import { num, textValue, ts } from "./analysis/edge-common.js";
import { analyzeStrengthSession, normalizeStrengthSets } from "./analysis/strength.js";
import { persistFitAnalysis } from "./analysis/persist-analysis.js";
import { chooseActivityMatch } from "./analysis/activity-match.js";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const VALID_TYPES=new Set(['football','futsal','run','cycling','gym']);
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
function localDate(instant:string|null){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(instant||Date.now()))}
async function resolveActivity({supabase,userId,fitRow,requestedType,startedAt,durationMin,distanceKm,avgHr,originalName}:{supabase:any,userId:string,fitRow:any,requestedType:string|null,startedAt:string|null,durationMin:number,distanceKm:number,avgHr:number|null,originalName:string}){
 if(fitRow.activity_id){const {data,error}=await supabase.from('activities').select('id,activity_type,source,external_id,metrics,title,duration_min,distance_km,avg_hr,started_at').eq('id',fitRow.activity_id).eq('user_id',userId).single();if(error||!data)throw new Error('Activity record not found');const type=requestedType||String(data.metrics?.fit_selected_sport||data.activity_type||'football');return{activity:data,type,matchedExisting:true,match:null,reanalysis:true}}
 if(!requestedType||!VALID_TYPES.has(requestedType))throw new Error('activity_type is required for a new FIT import');
 let candidates:any[]=[];if(startedAt){const t=Date.parse(startedAt),from=new Date(t-20*60000).toISOString(),to=new Date(t+20*60000).toISOString();const {data,error}=await supabase.from('activities').select('id,activity_type,source,external_id,metrics,title,duration_min,distance_km,avg_hr,started_at').eq('user_id',userId).eq('source','health_connect').gte('started_at',from).lte('started_at',to).limit(12);if(!error&&Array.isArray(data))candidates=data}
 const match=chooseActivityMatch({startedAt,durationMin,distanceKm,avgHr},candidates);if(match)return{activity:match.activity,type:requestedType,matchedExisting:true,match,reanalysis:false};
 const storageType=requestedType==='futsal'?'football':requestedType;const {data:created,error:createError}=await supabase.from('activities').insert({user_id:userId,activity_date:localDate(startedAt),started_at:startedAt,activity_type:storageType,source:'fit',external_id:`fit:${fitRow.id}`,title:originalName,metrics:{fit_enriched:true,fit_file_id:fitRow.id,fit_selected_sport:requestedType}}).select('id,activity_type,source,external_id,metrics,title,duration_min,distance_km,avg_hr,started_at').single();if(createError||!created)throw new Error(createError?.message||'Could not create FIT activity');return{activity:created,type:requestedType,matchedExisting:false,match:null,reanalysis:false}
}
const handler={async fetch(req:Request){
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);const auth=req.headers.get('Authorization');if(!auth)return json({error:'Missing authorization'},401);const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const token=auth.replace(/^Bearer\s+/i,''),{data:userData,error:userError}=await supabase.auth.getUser(token);if(userError||!userData.user)return json({error:'Unauthorized'},401);const userId=userData.user.id;
 let body:any;try{body=await req.json()}catch{return json({error:'Invalid JSON'},400)}const fitFileId=body?.fit_file_id,requestedType=body?.activity_type?String(body.activity_type):null;if(!fitFileId)return json({error:'fit_file_id is required'},400);if(requestedType&&!VALID_TYPES.has(requestedType))return json({error:'Unsupported activity_type'},400);
 const {data:fitRow,error:fitError}=await supabase.from('fit_files').select('id,user_id,activity_id,storage_path,original_name').eq('id',fitFileId).single();if(fitError||!fitRow)return json({error:'FIT record not found'},404);if(fitRow.user_id!==userId)return json({error:'Forbidden'},403);if(!fitRow.storage_path)return json({error:'FIT record is incomplete'},400);if(!fitRow.storage_path.startsWith(userId+'/')||fitRow.storage_path.split('/').some((p:string)=>p==='..'||p==='.'))return json({error:'Invalid FIT path'},403);await supabase.from('fit_files').update({parse_status:'processing',parse_error:null}).eq('id',fitFileId);
 try{const {data:blob,error:dlError}=await supabase.storage.from('fit-files').download(fitRow.storage_path);if(dlError||!blob)throw new Error(dlError?.message||'Could not download FIT');const bytes=await blob.arrayBuffer();if(bytes.byteLength>20*1024*1024)throw new Error('FIT exceeds 20 MB limit');if(bytes.byteLength<12||new TextDecoder().decode(new Uint8Array(bytes,8,4))!=='.FIT')throw new Error('Invalid FIT header');
 const parser=new FitParser({mode:'list',speedUnit:'km/h',lengthUnit:'km',elapsedRecordField:true,force:false}),parsed:any=await parser.parseAsync(bytes),records:any[]=Array.isArray(parsed.records)?parsed.records:[],sessions:any[]=Array.isArray(parsed.sessions)?parsed.sessions:[],session=sessions[0]||{},strengthSets=normalizeStrengthSets(parsed),fitSport=textValue(session.sport??parsed?.activity?.sport??parsed?.sport),fitSubSport=textValue(session.sub_sport??session.subSport??parsed?.activity?.sub_sport);if(!records.length&&!sessions.length&&!strengthSets.length)throw new Error('No activity records found in FIT');
 const profileRes=await supabase.from('profiles').select('hr_max_bpm').eq('user_id',userId).maybeSingle(),configuredMax=num(profileRes.data?.hr_max_bpm),base=buildBaseFitAnalysis(records,session,configuredMax),{pts,hrZones,speedZones,trackPoints}=base;const startMs=pts[0]?.t??ts(session.start_time??session.timestamp),startedAt=startMs?new Date(startMs).toISOString():null,durationMin=Number(base.summary.durationSec||0)/60,distanceKm=Number(base.summary.distanceKm||0),avgHr=base.summary.avgHr==null?null:Number(base.summary.avgHr);
 const resolved=await resolveActivity({supabase,userId,fitRow,requestedType,startedAt,durationMin,distanceKm,avgHr,originalName:fitRow.original_name});const activityType=resolved.type,storageActivityType=activityType==='futsal'?'football':activityType,activityId=resolved.activity.id;const totalReps=strengthSets.reduce((sum:number,x:any)=>sum+(x.reps||0),0),totalVolumeKg=strengthSets.reduce((sum:number,x:any)=>sum+((x.reps||0)*(x.weight_kg||0)),0),exerciseNames=[...new Set(strengthSets.map((x:any)=>x.exercise).filter(Boolean))].slice(0,20);const summary:any={activityType,activityVariant:activityType==='futsal'?'futsal':null,fitSport,fitSubSport,strengthSetCount:strengthSets.length,totalReps,totalVolumeKg:+totalVolumeKg.toFixed(1),exercises:exerciseNames,...base.summary};
 let footballDeep:any=null;if(activityType==='football'&&pts.length){footballDeep=analyzeFootballSession(pts,summary);if(footballDeep?.summaryPatch)Object.assign(summary,footballDeep.summaryPatch)}let futsalDeep:any=null;if(activityType==='futsal'&&pts.length){futsalDeep=analyzeFutsalSession(pts,summary);if(futsalDeep?.summaryPatch)Object.assign(summary,futsalDeep.summaryPatch)}let runningDeep:any=null;if(activityType==='run'&&pts.length){runningDeep=analyzeRunningSession(pts,summary);if(runningDeep?.summaryPatch)Object.assign(summary,runningDeep.summaryPatch)}let cyclingDeep:any=null;if(activityType==='cycling'&&pts.length){cyclingDeep=analyzeCyclingSession(pts,summary,session);if(cyclingDeep?.summaryPatch)Object.assign(summary,cyclingDeep.summaryPatch)}let strengthDeep:any=null;if(activityType==='gym'){strengthDeep=analyzeStrengthSession(strengthSets,summary);if(strengthDeep?.summaryPatch)Object.assign(summary,strengthDeep.summaryPatch)}
 const report=strengthDeep?.report||footballDeep?.report||futsalDeep?.report||runningDeep?.report||cyclingDeep?.report||makeReport(summary);if(!pts.length&&activityType!=='gym')report.analysis='El archivo incluye métricas de sesión, pero no muestras temporales. No se pueden calcular zonas, sprints ni distribución del esfuerzo.';const activityDate=localDate(startedAt),analysisVersion=footballDeep?'fit-v4-football-v1':futsalDeep?'fit-v8-futsal-v1':runningDeep?'fit-v5-running-v1':cyclingDeep?'fit-v6-cycling-v1':strengthDeep?'fit-v7-strength-v1':'fit-v8';await persistFitAnalysis({supabase,userId,fitFileId,activityId,activityType,storageActivityType,startedAt,activityDate,totalDurationSec:Number(summary.durationSec||0),distanceKm:Number(summary.distanceKm||0),avgHr:Number(summary.avgHr||0),maxHr:Number(summary.maxHr||0),calories:Number(summary.calories||0),rawTop:Number(summary.rawTopKmh||0),highIntensityM:Number(summary.highIntensityM||0),summary,report,hrZones,speedZones,trackPoints,sampleCount:pts.length,strengthSets,analysisVersion,existingMetrics:resolved.activity.metrics||{},parserVersion:'fit-v8 / fit-file-parser@5.0.2'});return json({ok:true,activity_id:activityId,activity_type:activityType,matched_existing:resolved.matchedExisting,reanalysis:resolved.reanalysis,match:resolved.match?{score:resolved.match.score,start_diff_min:resolved.match.startDiffMin,duration_diff_min:resolved.match.durationDiffMin,distance_diff_km:resolved.match.distanceDiffKm}:null,summary,report,track_points:trackPoints.length,strength_sets:strengthSets.length});
 }catch(e){const message=e instanceof Error?e.message:String(e);await supabase.from('fit_files').update({parse_status:'error',parse_error:message}).eq('id',fitFileId);return json({error:message},422)}
}};Deno.serve((req:Request)=>handler.fetch(req));export default handler;
