const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const round=(v,d=1)=>finite(v)?+Number(v).toFixed(d):null;
const mean=values=>{const a=values.map(Number).filter(Number.isFinite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null};
const percentile=(values,q)=>{const a=values.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const p=Math.max(0,Math.min(1,q))*(a.length-1),lo=Math.floor(p),hi=Math.ceil(p),f=p-lo;return a[lo]*(1-f)+a[hi]*f};

function normalize(points=[]){
 const raw=(Array.isArray(points)?points:[]).map(p=>({t:Number(p?.t),speedKmh:finite(p?.speed)?Number(p.speed):finite(p?.speedKmh)?Number(p.speedKmh):finite(p?.speed_kmh)?Number(p.speed_kmh):null,distanceKm:finite(p?.distanceKm)?Number(p.distanceKm):finite(p?.distance_km)?Number(p.distance_km):null,hr:finite(p?.hr)?Number(p.hr):null,altitudeM:finite(p?.altitudeKm)?Number(p.altitudeKm)*1000:finite(p?.altitude_m)?Number(p.altitude_m):null,cadenceRpm:finite(p?.cadenceSpm)?Number(p.cadenceSpm):finite(p?.cadence_rpm)?Number(p.cadence_rpm):null,powerW:finite(p?.powerW)?Number(p.powerW):finite(p?.power_w)?Number(p.power_w):null})).filter(p=>Number.isFinite(p.t)).sort((a,b)=>a.t-b.t);
 if(!raw.length)return[];const t0=raw[0].t,out=[];let cumulativeM=0;
 for(let i=0;i<raw.length;i++){
  const p=raw[i],prev=i?raw[i-1]:null,dt=prev?(p.t-prev.t)/1000:0,validDt=dt>0&&dt<=15?dt:0;
  let speed=finite(p.speedKmh)?Number(p.speedKmh):null;if(speed!==null&&(speed<0||speed>120))speed=null;
  let cadence=finite(p.cadenceRpm)?Number(p.cadenceRpm):null;if(cadence!==null&&(cadence<10||cadence>220))cadence=null;
  let power=finite(p.powerW)?Number(p.powerW):null;if(power!==null&&(power<0||power>2500))power=null;
  let dIncM=0;if(prev&&validDt&&finite(prev.distanceKm)&&finite(p.distanceKm)&&p.distanceKm>=prev.distanceKm)dIncM=(p.distanceKm-prev.distanceKm)*1000;if(!Number.isFinite(dIncM)||dIncM<0||dIncM/Math.max(validDt,.1)>120/3.6)dIncM=0;cumulativeM+=dIncM;
  let elevDeltaM=0;if(prev&&finite(prev.altitudeM)&&finite(p.altitudeM)){const d=Number(p.altitudeM)-Number(prev.altitudeM);if(Math.abs(d)>=.8&&Math.abs(d)<=35)elevDeltaM=d}
  out.push({tSec:(p.t-t0)/1000,dt:validDt,speedKmh:speed,dIncM,cumulativeM,hr:p.hr,altitudeM:p.altitudeM,elevDeltaM,cadenceRpm:cadence,powerW:power});
 }
 return out;
}
const moving=s=>finite(s.speedKmh)?Number(s.speedKmh)>=3:(Number(s.dIncM)||0)>0;
function aggregate(samples,startSec,endSec){
 let distanceM=0,movingSec=0,hrSum=0,hrTime=0,speedSum=0,speedTime=0,powerSum=0,powerTime=0,cadSum=0,cadTime=0,gain=0,loss=0;
 for(const s of samples){if(s.tSec<=startSec||s.tSec>endSec)continue;const dt=Number(s.dt)||0;distanceM+=Number(s.dIncM)||0;if(moving(s)){movingSec+=dt;if(finite(s.speedKmh)){speedSum+=Number(s.speedKmh)*dt;speedTime+=dt}}if(finite(s.hr)){hrSum+=Number(s.hr)*dt;hrTime+=dt}if(finite(s.powerW)){powerSum+=Number(s.powerW)*dt;powerTime+=dt}if(finite(s.cadenceRpm)){cadSum+=Number(s.cadenceRpm)*dt;cadTime+=dt}const e=Number(s.elevDeltaM)||0;if(e>0)gain+=e;else loss+=Math.abs(e)}
 return{distanceM:round(distanceM,0),movingSec:round(movingSec,0),avgSpeedKmh:speedTime?round(speedSum/speedTime,2):null,avgHr:hrTime?Math.round(hrSum/hrTime):null,avgPowerW:powerTime?Math.round(powerSum/powerTime):null,avgCadenceRpm:cadTime?round(cadSum/cadTime,1):null,elevationGainM:round(gain,1),elevationLossM:round(loss,1)};
}
function powerSummary(samples,session={}){
 const valid=samples.filter(s=>finite(s.powerW)&&s.dt>0),duration=valid.reduce((n,s)=>n+s.dt,0),joules=valid.reduce((n,s)=>n+Number(s.powerW)*s.dt,0),values=valid.map(s=>Number(s.powerW)),sessionAvg=finite(session.avg_power)?Number(session.avg_power):null,sessionMax=finite(session.max_power)?Number(session.max_power):null,normalized=finite(session.normalized_power)?Number(session.normalized_power):null,totalWorkJ=finite(session.total_work)?Number(session.total_work):null,ftpRaw=session.threshold_power??session.functional_threshold_power??session.ftp,ftp=finite(ftpRaw)&&Number(ftpRaw)>=50&&Number(ftpRaw)<=800?Number(ftpRaw):null;
 const available=valid.length>=20||sessionAvg!==null||sessionMax!==null||totalWorkJ!==null,avgW=valid.length>=20?joules/duration:sessionAvg,maxW=values.length?Math.max(...values):sessionMax,robustW=values.length>=20?percentile(values,.95):null,kJ=duration>=30?joules/1000:(totalWorkJ!==null?totalWorkJ/1000:null),coverageSec=round(duration,0);
 const zones=[];
 if(ftp&&duration>=120){const bounds=[0,.55,.75,.90,1.05,1.20,1.50,99];for(let i=0;i<7;i++)zones.push({zone:i+1,min_w:Math.round(ftp*bounds[i]),max_w:i===6?null:Math.round(ftp*bounds[i+1]),seconds:0});for(const s of valid){const ratio=Number(s.powerW)/ftp;let zi=0;if(ratio>.55)zi=1;if(ratio>.75)zi=2;if(ratio>.90)zi=3;if(ratio>1.05)zi=4;if(ratio>1.20)zi=5;if(ratio>1.50)zi=6;zones[zi].seconds+=s.dt}for(const z of zones)z.seconds=round(z.seconds,1)}
 return{available,seriesAvailable:valid.length>=20,avgPowerW:round(avgW,0),maxPowerW:round(maxW,0),robustPowerW:round(robustW,0),normalizedPowerW:round(normalized,0),workKj:round(kJ,1),ftpW:ftp,zonesAvailable:zones.length>0,zones,coverageSec,samples:valid.length};
}
function cadenceSummary(samples){const valid=samples.filter(s=>moving(s)&&finite(s.cadenceRpm)&&s.dt>0),time=valid.reduce((n,s)=>n+s.dt,0);return{available:valid.length>=20,avgRpm:time?round(valid.reduce((n,s)=>n+Number(s.cadenceRpm)*s.dt,0)/time,1):null,p95Rpm:valid.length?round(percentile(valid.map(s=>s.cadenceRpm),.95),1):null,samples:valid.length}}
function pauseSummary(samples){let sec=0,count=0,run=0;for(const s of samples.slice(1)){if(!s.dt)continue;if(!moving(s)){sec+=s.dt;run+=s.dt}else{if(run>=5)count++;run=0}}if(run>=5)count++;return{pauseSec:round(sec,0),stopCount:count}}
function elevationSummary(samples){const alt=samples.filter(s=>finite(s.altitudeM)).map(s=>Number(s.altitudeM));let gain=0,loss=0;for(const s of samples){const d=Number(s.elevDeltaM)||0;if(d>0)gain+=d;else loss+=Math.abs(d)}return{available:alt.length>=10,gainM:round(gain,1),lossM:round(loss,1),minM:alt.length?round(Math.min(...alt),1):null,maxM:alt.length?round(Math.max(...alt),1):null}}
function halves(samples,durationSec){if(durationSec<600)return{available:false,reason:'Duración insuficiente'};const mid=durationSec/2,a=aggregate(samples,0,mid),b=aggregate(samples,mid,durationSec);if(!finite(a.avgSpeedKmh)||!finite(b.avgSpeedKmh))return{available:false,reason:'Velocidad insuficiente'};const speedChange=(b.avgSpeedKmh-a.avgSpeedKmh)/a.avgSpeedKmh*100;return{available:true,first:a,second:b,speedChangePct:round(speedChange,2)}}
function cardiacDrift(h){if(!h.available||!finite(h.first.avgHr)||!finite(h.second.avgHr)||!finite(h.first.avgSpeedKmh)||!finite(h.second.avgSpeedKmh))return{available:false,label:'Datos insuficientes',driftPct:null};const e1=h.first.avgSpeedKmh/h.first.avgHr,e2=h.second.avgSpeedKmh/h.second.avgHr,drift=(e1-e2)/e1*100,speedDelta=Math.abs(h.speedChangePct),elevDelta=Math.abs((h.second.elevationGainM||0)-(h.first.elevationGainM||0)),comparable=speedDelta<=15&&elevDelta<=150;let label='Deriva baja',level='low';if(drift>=7){label='Deriva notable';level='notable'}else if(drift>=3.5){label='Deriva moderada';level='moderate'}else if(drift<0){label='Sin deriva apreciable';level='none'}return{available:true,comparable,label,level,driftPct:round(drift,2),speedDifferencePct:round(speedDelta,2),elevationGainDifferenceM:round(elevDelta,1)}}

function buildReport(m,d){
 const strengths=[],improvements=[],highlights=[];
 if(d.halves.available&&d.halves.speedChangePct>=3)strengths.push(`La segunda mitad fue ${d.halves.speedChangePct.toFixed(1)} % más rápida.`);
 if(d.drift.available&&d.drift.comparable&&['none','low'].includes(d.drift.level))strengths.push(`La relación velocidad/FC se mantuvo estable (deriva ${d.drift.driftPct.toFixed(1)} %).`);
 if(d.power.available&&d.power.avgPowerW)strengths.push(`Potencia media registrada: ${Math.round(d.power.avgPowerW)} W${d.power.workKj?` y ${Math.round(d.power.workKj)} kJ`:''}.`);
 if(d.drift.available&&d.drift.comparable&&d.drift.level==='notable')improvements.push(`La eficiencia velocidad/FC cayó ${d.drift.driftPct.toFixed(1)} % entre mitades; interprétalo junto al desnivel y el objetivo de la salida.`);
 if(d.halves.available&&d.halves.speedChangePct<=-6)improvements.push(`La velocidad media bajó ${Math.abs(d.halves.speedChangePct).toFixed(1)} % en la segunda mitad.`);
 if(!strengths.length)strengths.push('Salida útil para construir tu referencia individual de ciclismo.');if(!improvements.length)improvements.push('Compara futuras salidas de terreno y duración similares antes de sacar conclusiones fuertes.');
 if(d.elevation.available)highlights.push(`Desnivel filtrado: +${Math.round(d.elevation.gainM)} / -${Math.round(d.elevation.lossM)} m.`);if(d.cadence.available)highlights.push(`Cadencia media: ${Math.round(d.cadence.avgRpm)} rpm.`);if(d.power.zonesAvailable)highlights.push(`Zonas de potencia calculadas con FTP/threshold de ${Math.round(d.power.ftpW)} W incluido en el FIT.`);else if(d.power.available)highlights.push('Hay datos de potencia, pero no se crean zonas sin un FTP/threshold válido en el FIT.');
 const powerSentence=d.power.available?` Potencia: ${d.power.avgPowerW??'—'} W de media${d.power.workKj?`, ${d.power.workKj.toFixed(0)} kJ`:''}.`:'';
 const analysis=`Salida de ${Number(m.distanceKm||0).toFixed(2)} km y ${Math.round(Number(m.movingTimeSec||0)/60)} min en movimiento, a ${Number(m.avgSpeedKmh||0).toFixed(1)} km/h de media.${powerSentence}`;
 return{version:'cycling-report-v1',sport:'cycling',analysis,strengths:strengths.slice(0,3),improvements:improvements.slice(0,3),highlights:highlights.slice(0,5),observations:[d.drift.available&&!d.drift.comparable?'La deriva cardíaca tiene comparabilidad limitada porque cambió bastante la velocidad o el desnivel.':null,!d.power.zonesAvailable&&d.power.available?'No se han inferido zonas de potencia: se necesita FTP/threshold explícito en el FIT.':null].filter(Boolean),sections:{resumen:{distancia_km:round(m.distanceKm,2),duracion_min:round(Number(m.durationSec||0)/60,1),tiempo_movimiento_min:round(Number(m.movingTimeSec||0)/60,1),velocidad_media_km_h:round(m.avgSpeedKmh,1),velocidad_robusta_p95_km_h:round(m.robustCyclingSpeedKmh,1),paradas_s:d.pauses.pauseSec,paradas_detectadas:d.pauses.stopCount},mitades:{disponible:d.halves.available,cambio_velocidad_segunda_mitad_pct:d.halves.speedChangePct??null,primera_mitad_km_h:d.halves.first?.avgSpeedKmh??null,segunda_mitad_km_h:d.halves.second?.avgSpeedKmh??null,primera_mitad_fc:d.halves.first?.avgHr??null,segunda_mitad_fc:d.halves.second?.avgHr??null},cardiaco:{deriva_disponible:d.drift.available,lectura:d.drift.label,deriva_pct:d.drift.driftPct,mitades_comparables:d.drift.available?d.drift.comparable:false,fc_media:m.avgHr??null,fc_maxima:m.maxHr??null},elevacion:{disponible:d.elevation.available,desnivel_positivo_m:d.elevation.gainM,desnivel_negativo_m:d.elevation.lossM,elevacion_min_m:d.elevation.minM,elevacion_max_m:d.elevation.maxM},cadencia:{disponible:d.cadence.available,cadencia_media_rpm:d.cadence.avgRpm,cadencia_p95_rpm:d.cadence.p95Rpm,muestras:d.cadence.samples},potencia:{disponible:d.power.available,serie_disponible:d.power.seriesAvailable,potencia_media_w:d.power.avgPowerW,potencia_max_w:d.power.maxPowerW,potencia_p95_w:d.power.robustPowerW,potencia_normalizada_w:d.power.normalizedPowerW,trabajo_kj:d.power.workKj,ftp_w:d.power.ftpW,zonas_disponibles:d.power.zonesAvailable,zonas:d.power.zones},calidad:{lectura:d.quality,muestras_temporales:d.samples,muestras_fc:d.hrSamples,muestras_potencia:d.power.samples,muestras_cadencia:d.cadence.samples}}};
}

export function analyzeCyclingSession(points=[],summary={},session={}){
 const samples=normalize(points);if(samples.length<2)return{summaryPatch:{cyclingAnalysisVersion:'cycling-v1'},report:null,details:null};const durationSec=finite(summary.durationSec)?Number(summary.durationSec):Number(samples.at(-1)?.tSec)||0,distanceKm=finite(summary.distanceKm)?Number(summary.distanceKm):(Number(samples.at(-1)?.cumulativeM)||0)/1000,movingSec=samples.reduce((n,s)=>n+(moving(s)?Number(s.dt)||0:0),0),speedValues=samples.filter(s=>moving(s)&&finite(s.speedKmh)).map(s=>Number(s.speedKmh)),avgSpeed=distanceKm&&movingSec?distanceKm/(movingSec/3600):mean(speedValues),robustSpeed=percentile(speedValues,.95),elevation=elevationSummary(samples),cadence=cadenceSummary(samples),pauses=pauseSummary(samples),half=halves(samples,durationSec),drift=cardiacDrift(half),power=powerSummary(samples,session),hrSamples=samples.filter(s=>finite(s.hr)).length,quality=samples.length>=120&&distanceKm>=3?'buena':samples.length>=20?'parcial':'insuficiente';
 const patch={cyclingAnalysisVersion:'cycling-v1',movingTimeSec:round(movingSec,0),avgSpeedKmh:round(avgSpeed,2),robustCyclingSpeedKmh:round(robustSpeed,2),elevationGainM:elevation.available?elevation.gainM:summary.elevationGainM??null,elevationLossM:elevation.available?elevation.lossM:null,avgCadenceRpm:cadence.available?cadence.avgRpm:null,p95CadenceRpm:cadence.available?cadence.p95Rpm:null,pauseSec:pauses.pauseSec,stopCount:pauses.stopCount,secondHalfSpeedChangePct:half.available?half.speedChangePct:null,cardiacDriftPct:drift.available?drift.driftPct:null,cardiacDriftLabel:drift.available?drift.label:null,avgPowerW:power.available?power.avgPowerW:null,maxPowerW:power.available?power.maxPowerW:null,robustPowerW:power.available?power.robustPowerW:null,normalizedPowerW:power.available?power.normalizedPowerW:null,cyclingWorkKj:power.available?power.workKj:null,cyclingFtpW:power.ftpW,powerZonesAvailable:power.zonesAvailable,cyclingDataQuality:quality};
 const merged={...summary,...patch,distanceKm,durationSec,movingTimeSec:patch.movingTimeSec},deep={samples:samples.length,hrSamples,elevation,cadence,pauses,halves:half,drift,power,quality};return{summaryPatch:patch,report:buildReport(merged,deep),details:deep};
}
