import {num,textValue,ts} from './edge-common.js';
const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const round=(v,d=1)=>finite(v)?+Number(v).toFixed(d):null;
function inferMuscleGroup(...parts){const t=parts.map(textValue).filter(Boolean).join(' ').toLowerCase().replace(/[_-]+/g,' ');if(!t)return null;if(/bench|chest|pectoral|push up/.test(t))return'pecho';if(/row|pull up|pullup|lat pull|back|espalda/.test(t))return'espalda';if(/shoulder|deltoid|overhead|hombro/.test(t))return'hombro';if(/bicep/.test(t))return'biceps';if(/tricep/.test(t))return'triceps';if(/calf|gemelo/.test(t))return'gemelos';if(/abdom|core|plank/.test(t))return'core';if(/deadlift|romanian|hamstring|isquio/.test(t))return'isquios';if(/glute|hip thrust/.test(t))return'gluteo';if(/squat|leg press|lunge|quadricep|extension/.test(t))return'cuadriceps';return null}
export function normalizeStrengthSets(parsed){const messages=parsed?.messages&&typeof parsed.messages==='object'?parsed.messages:{},raw=[...(Array.isArray(messages.set)?messages.set:[]),...(Array.isArray(messages.exercise_set)?messages.exercise_set:[])];return raw.map((x,i)=>{const reps=num(x.repetitions??x.reps??x.num_reps),weight=num(x.weight??x.weight_kg??x.resistance),setType=textValue(x.set_type??x.type),category=textValue(x.category??x.exercise_category),subtype=textValue(x.category_subtype??x.exercise_name??x.exercise_subtype),start=ts(x.start_time??x.timestamp),duration=num(x.duration??x.total_timer_time),exercise=subtype||category||'Serie FIT';return{index:Number(x.message_index??i+1),performed_at:start?new Date(start).toISOString():null,exercise,muscle_group:inferMuscleGroup(category,subtype,exercise),reps:reps!=null?Math.round(reps):null,weight_kg:weight,set_type:setType,duration_sec:duration,category,category_subtype:subtype,raw:{message_index:x.message_index??null,weight_display_unit:textValue(x.weight_display_unit)}}}).filter(x=>x.reps!=null||x.weight_kg!=null||x.category!=null||x.category_subtype!=null||x.set_type!=null)}
function isRestSet(x){return /rest|recovery|pause|descanso/.test(String(x?.set_type||'').toLowerCase())}
function e1rm(weight,reps){if(!finite(weight)||!finite(reps)||Number(weight)<=0||Number(reps)<1||Number(reps)>12)return null;return Number(weight)*(1+Number(reps)/30)}
export function analyzeStrengthSession(sets=[],summary={}){
 const all=Array.isArray(sets)?sets:[],working=all.filter(x=>!isRestSet(x)&&finite(x.reps)&&Number(x.reps)>0),withLoad=working.filter(x=>finite(x.weight_kg)&&Number(x.weight_kg)>0),exerciseMap=new Map(),muscleMap=new Map();let reps=0,volume=0;
 for(const x of working){const r=Number(x.reps)||0,w=finite(x.weight_kg)?Number(x.weight_kg):0;reps+=r;volume+=r*w;const name=String(x.exercise||'Ejercicio FIT'),key=name.toLowerCase(),g=exerciseMap.get(key)||{exercise:name,sets:0,reps:0,volumeKg:0,maxWeightKg:null,bestE1rmKg:null,muscleGroup:x.muscle_group||null};g.sets++;g.reps+=r;g.volumeKg+=r*w;if(w>0)g.maxWeightKg=g.maxWeightKg==null?w:Math.max(g.maxWeightKg,w);const est=e1rm(w,r);if(est)g.bestE1rmKg=g.bestE1rmKg==null?est:Math.max(g.bestE1rmKg,est);exerciseMap.set(key,g);const muscle=x.muscle_group||'sin_clasificar';muscleMap.set(muscle,(muscleMap.get(muscle)||0)+r*w)}
 const exercises=[...exerciseMap.values()].map(x=>({...x,volumeKg:round(x.volumeKg,1),bestE1rmKg:round(x.bestE1rmKg,1),maxWeightKg:round(x.maxWeightKg,1)})).sort((a,b)=>b.volumeKg-a.volumeKg),muscles=[...muscleMap.entries()].map(([muscle,volumeKg])=>({muscle,volumeKg:round(volumeKg,1),sharePct:volume>0?round(volumeKg/volume*100,1):null})).sort((a,b)=>b.volumeKg-a.volumeKg),best=exercises.filter(x=>finite(x.bestE1rmKg)).sort((a,b)=>b.bestE1rmKg-a.bestE1rmKg)[0]||null,durationMin=Number(summary.durationSec||0)/60,density=durationMin>0&&volume>0?volume/durationMin:null,weightedSets=withLoad.length,dataQuality=working.length>=3?(weightedSets/working.length>=.7?'buena':'parcial'):(working.length?'parcial':'insuficiente');
 const patch={strengthAnalysisVersion:'strength-v1',strengthSetCount:working.length,totalReps:reps,totalVolumeKg:round(volume,1),weightedSetCount:weightedSets,exerciseCount:exercises.length,muscleGroupCount:muscles.filter(x=>x.muscle!=='sin_clasificar').length,volumeDensityKgPerMin:round(density,1),bestEstimated1RmKg:best?.bestE1rmKg??null,bestEstimated1RmExercise:best?.exercise??null,strengthDataQuality:dataQuality};
 const strengths=[],improvements=[],highlights=[];if(volume>0)strengths.push(`Volumen externo registrado: ${Math.round(volume)} kg·rep en ${working.length} series de trabajo.`);if(best)strengths.push(`Mejor 1RM estimado de la sesión: ${best.bestE1rmKg.toFixed(1)} kg en ${best.exercise}.`);if(exercises.length>=3)strengths.push(`Trabajo repartido entre ${exercises.length} ejercicios detectados.`);if(!working.length)improvements.push('El FIT no contiene series de trabajo reconocibles; no se inventan repeticiones ni cargas.');else if(weightedSets<working.length*.5)improvements.push('Muchas series no incluyen carga externa; el volumen en kg·rep es incompleto.');else improvements.push('Compara el mismo ejercicio entre sesiones por carga, repeticiones y volumen, no solo por tonelaje total.');if(muscles[0]&&muscles[0].muscle!=='sin_clasificar')highlights.push(`Mayor volumen clasificado: ${muscles[0].muscle} (${Math.round(muscles[0].volumeKg)} kg·rep).`);if(density)highlights.push(`Densidad de volumen: ${density.toFixed(0)} kg·rep/min.`);if(exercises[0])highlights.push(`Ejercicio con más volumen: ${exercises[0].exercise} (${Math.round(exercises[0].volumeKg)} kg·rep).`);
 const analysis=working.length?`Entrenamiento de fuerza con ${working.length} series de trabajo y ${reps} repeticiones detectadas.${volume>0?` Volumen externo: ${Math.round(volume)} kg·rep.`:''} El 1RM mostrado, cuando existe, es una estimación matemática y no una prueba máxima.`:'El FIT se ha procesado como fuerza, pero no contiene series de trabajo suficientemente detalladas para un análisis profundo.';
 const report={version:'strength-report-v1',sport:'gym',analysis,strengths:strengths.length?strengths:['Sesión conservada para construir el histórico de fuerza.'],improvements,highlights,observations:[best?'El 1RM estimado usa la fórmula de Epley solo en series de 1–12 repeticiones con carga válida.':null,dataQuality!=='buena'?'La calidad del análisis depende de que el dispositivo guarde peso, repeticiones y tipo de serie.':null].filter(Boolean),sections:{resumen:{series_trabajo:working.length,repeticiones:reps,volumen_kg_rep:round(volume,1),series_con_peso:weightedSets,ejercicios:exercises.length,grupos_musculares:patch.muscleGroupCount,densidad_kg_rep_min:patch.volumeDensityKgPerMin},mejor_estimacion:{ejercicio:best?.exercise??null,estimacion_1rm_kg:best?.bestE1rmKg??null,peso_maximo_registrado_kg:best?.maxWeightKg??null,nota:best?'Estimación Epley; no es un 1RM medido.':'Sin datos suficientes.'},distribucion:{grupo_principal:muscles[0]?.muscle??null,volumen_grupo_principal_kg_rep:muscles[0]?.volumeKg??null,porcentaje_grupo_principal:muscles[0]?.sharePct??null,ejercicio_mayor_volumen:exercises[0]?.exercise??null,volumen_ejercicio_principal_kg_rep:exercises[0]?.volumeKg??null},calidad:{lectura:dataQuality,series_totales_fit:all.length,series_trabajo:working.length,series_con_carga:weightedSets}},details:{exercises,muscles}};
 return{summaryPatch:patch,report,details:{workingSets:working.length,exercises,muscles,dataQuality}};
}
export function makeStrengthReport(m){const sets=Number(m.strengthSetCount||0),reps=Number(m.totalReps||0),volume=Number(m.totalVolumeKg||0),strengths=[],improvements=[];if(sets)strengths.push(`Sesión registrada con ${sets} series${reps?` y ${reps} repeticiones`:''}.`);if(volume>0)strengths.push(`Volumen externo registrado: ${Math.round(volume)} kg·rep.`);if(m.avgHr)strengths.push(`Respuesta cardiovascular registrada durante la fuerza: ${m.avgHr} ppm de media.`);if(!sets)improvements.push('Este FIT no contiene detalle reconocible de series; registra las series manualmente si quieres comparar progresión de fuerza.');else improvements.push('Compara próximas sesiones del mismo ejercicio por carga, repeticiones, RIR/RPE y volumen total.');return{analysis:sets?`Entrenamiento de fuerza con ${sets} series detectadas${reps?` y ${reps} repeticiones`:''}. ${volume>0?`El volumen registrado fue de ${Math.round(volume)} kg·rep. `:''}Training Lab conservará cada serie para comparar la progresión por ejercicio.`:'El FIT se ha procesado como entrenamiento de fuerza, pero el dispositivo no ha incluido mensajes de series suficientemente detallados. Se conservan duración, frecuencia cardíaca y demás métricas disponibles.',strengths,improvements};}
